### ISSUE TITLE
rust build fails w/ globset-0.2.0 for x86_64-musl

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#10555]
```
=> rust-1.22.1_1: building (dependency of firefox) ...
   [host] cmake-3.10.1_1: found (/host/binpkgs)
   [host] curl-7.57.0_2: found (/host/binpkgs)
   [host] pkg-config-0.29.2_1: found (/host/binpkgs)
   [host] python-2.7.14_1: found (/host/binpkgs)
   [host] libcurl-7.57.0_2: found (/host/binpkgs)
   [host] libgit2-0.26.0_1: found (/host/binpkgs)
   [target] libffi-devel-3.2.1_4: found (/host/binpkgs)
   [target] llvm3.9-3.9.1_2: found (/host/binpkgs)
   [target] ncurses-devel-6.0_2: found (/host/binpkgs)
   [target] zlib-devel-1.2.11_2: found (/host/binpkgs)
=> rust: building (dependency of firefox) ...
=> rust-1.22.1_1: installing host dependency 'cmake-3.10.1_1' ...
=> rust-1.22.1_1: installing host dependency 'curl-7.57.0_2' ...
=> rust-1.22.1_1: installing host dependency 'pkg-config-0.29.2_1' ...
=> rust-1.22.1_1: installing host dependency 'python-2.7.14_1' ...
=> rust-1.22.1_1: installing host dependency 'libcurl-7.57.0_2' ...
=> rust-1.22.1_1: installing host dependency 'libgit2-0.26.0_1' ...
=> rust-1.22.1_1: installing target dependency 'libffi-devel-3.2.1_4' ...
=> rust-1.22.1_1: installing target dependency 'llvm3.9-3.9.1_2' ...
=> rust-1.22.1_1: installing target dependency 'ncurses-devel-6.0_2' ...
=> rust-1.22.1_1: installing target dependency 'zlib-devel-1.2.11_2' ...
=> rust-1.22.1_1: running do-fetch hook: 00-distfiles ...
=> rust-1.22.1_1: running do-extract hook: 00-distfiles ...
=> rust-1.22.1_1: extracting distfile(s), please wait...
=> rust-1.22.1_1: running post_extract ...
=> rust-1.22.1_1: running post-extract hook: 00-patches ...
=> rust-1.22.1_1: patching: link-musl-dynamically.patch.
=> rust-1.22.1_1: patching: llvm-with-ffi.patch.
=> rust-1.22.1_1: running pre-configure hook: 00-gnu-configure-asneeded ...
=> rust-1.22.1_1: running pre-configure hook: 01-override-config ...
=> rust-1.22.1_1: running pre-configure hook: 02-script-wrapper ...
=> rust-1.22.1_1: running do_configure ...
configure: processing command line
configure: 
configure: rust.channel         := stable
configure: build.docs           := False
configure: rust.rpath           := False
configure: build.host           := ['x86_64-unknown-linux-musl']
configure: target.x86_64-unknown-linux-musl.musl-root := /usr
configure: install.prefix       := /usr
configure: build.build          := x86_64-unknown-linux-musl
configure: build.rustc          := /builddir/rustc-1.22.1-src/stage0/bin/rustc
configure: build.cargo          := /builddir/rustc-1.22.1-src/stage0/bin/cargo
configure: target.x86_64-unknown-linux-musl.llvm-config := /usr/bin/llvm-config
configure: rust.codegen-tests   := False
configure: rust.use-jemalloc    := False
configure: llvm.ccache          := True
configure: build.configure-args := ['--prefix=/usr', '--host=x86_64-unknown-linux ...
configure: 
configure: writing `config.toml` in current directory
configure: 
configure: run `python ./src/bootstrap/x.py --help`
configure: 
=> rust-1.22.1_1: running pre-build hook: 02-script-wrapper ...
=> rust-1.22.1_1: running pre_build ...
=> rust-1.22.1_1: running do_build ...
/usr/bin/python2.7 /builddir/rustc-1.22.1-src/src/bootstrap/bootstrap.py dist -v
running: /builddir/rustc-1.22.1-src/stage0/bin/cargo build --manifest-path /builddir/rustc-1.22.1-src/src/bootstrap/Cargo.toml --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/rust-lang/cargo`
error: failed to select a version for `globset` (required by `ignore`):
all possible versions conflict with previously selected versions of `globset`
  version 0.2.0 in use by globset v0.2.0
  possible versions to select: 0.2.1
Traceback (most recent call last):
  File "/builddir/rustc-1.22.1-src/src/bootstrap/bootstrap.py", line 767, in <module>
    main()
  File "/builddir/rustc-1.22.1-src/src/bootstrap/bootstrap.py", line 750, in main
    bootstrap()
  File "/builddir/rustc-1.22.1-src/src/bootstrap/bootstrap.py", line 730, in bootstrap
    build.build_bootstrap()
  File "/builddir/rustc-1.22.1-src/src/bootstrap/bootstrap.py", line 618, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "/builddir/rustc-1.22.1-src/src/bootstrap/bootstrap.py", line 148, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /builddir/rustc-1.22.1-src/stage0/bin/cargo build --manifest-path /builddir/rustc-1.22.1-src/src/bootstrap/Cargo.toml --verbose
make: *** [Makefile:70: dist] Error 1
=> ERROR: rust-1.22.1_1: failed to run do_build() at line 14.
```

**Comment by pullmoll** [comment]
[rust 1.23.0 is out](https://www.rust-lang.org/en-US/) on Jan 4th 2018

**Comment by chneukirchen** [comment]
At it.

**Comment by pullmoll** [comment]
Hmm.. `_date=2017-10-28` is gone at https://dev-static.rust-lang.org/dist/
Perhaps use the latest `2018-01-02` ?

**Comment by pullmoll** [comment]
I'm building locally for i686 with `_date=2018-01-02`, ` distfiles+="https://dev-static.rust-lang.org/dist/${_date}/cargo-0.24.0-i686-unknown-linux-gnu.tar.xz"` and `checksum+="6ffc847e0ee2a1273223ce500f7b212d051e99a6d234e34585d0c55e21a963ea"` for a try.

**Comment by pullmoll** [comment]
And x86_64 also succeeded with `_date=2018-01-02` and:
```
x86_64)
        # extract from src/stage0.txt
        distfiles+="
         https://dev-static.rust-lang.org/dist/2017-11-20/rustc-1.22.0-x86_64-unknown-linux-gnu.tar.gz
         https://dev-static.rust-lang.org/dist/2017-11-20/rust-std-1.22.0-x86_64-unknown-linux-gnu.tar.gz
         https://dev-static.rust-lang.org/dist/${_date}/cargo-0.24.0-x86_64-unknown-linux-gnu.tar.xz"
        checksum+="
         a54835b06f960cb04507136a6491e561271374701bc38a8e8fd085f9e78e12e6
         c065c4958444955968aae60a3724bea177ddabf364c5b8cf29a08dd5d1e7df6f
         93b953c8c7a2088aef952de8dccd7f6ccf9b21bf94b735d3909961ffe831da8c"
        ;;
```

**Comment by chneukirchen** [comment]
Fine with me too.

**Comment by pullmoll** [comment]
Ok, then this can be closed.
