### ISSUE TITLE
virt-manager, not able to create a LinuxVM

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#1093]
Create a new Linux VM create

unsupported configuration: USB redirection is not supported by this version of QEMU»

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 89, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/create.py", line 1855, in do_install
    guest.start_install(meter=meter)
  File "/usr/share/virt-manager/virtinst/guest.py", line 405, in start_install
    noboot)
  File "/usr/share/virt-manager/virtinst/guest.py", line 469, in _create_guest
    dom = self.conn.createLinux(start_xml or final_xml, 0)
  File "/usr/lib/python2.7/site-packages/libvirt.py", line 3497, in createLinux
    if ret is None:raise libvirtError('virDomainCreateLinux() failed', conn=self)
libvirtError: unsupported configuration: USB redirection is not supported by this version of QEMU

**Comment by pulux** [comment]
update:

only if Console is on Spice not on VNC

**Comment by thypon** [comment]
duplicate
