### ISSUE TITLE
Mailpile don't startup

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1180]
```
Traceback (most recent call last):
  File "/usr/bin/mailpile", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3023, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 920, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 807, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: lockfile>=0.2
```

installing manually `python-lockfile` solves the problem

**Comment by xtraeme** [comment]
Assigned to maintainer.
