### ISSUE TITLE
Package request: paperwork

### ISSUE THREAD

**Issue by icf20** [voidlinux/void-packages#12183]
https://github.com/openpaperwork/paperwork

this app is quite awesome to ocr pdf and to manage metadata for scanned or imported pdf

**Comment by cr6git** [comment]
````
$ paperwork
Traceback (most recent call last):
  File "/usr/bin/paperwork", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3086, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3099, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pypillowfight' distribution was not found and is required by paperwork
````
We also need to package [pillowfight](https://github.com/openpaperwork/libpillowfight) in order for this to work.

**Comment by cr6git** [comment]
Here's a first draft of template:
````
# Template file for 'paperwork'
pkgname=paperwork
version=1.2.4
revision=1
noarch=yes
build_style=gnu-makefile
hostmakedepends="git python3-Pillow python3-dateutil python3-enchant
 python3-pycountry python3-setuptools python3-termcolor python3-xdg"
makedepends="python3-devel"
depends="python3-Pillow python3-dateutil python3-enchant
 python3-pycountry python3-setuptools python3-termcolor python3-xdg"
short_desc="Personal document manager"
maintainer="local <root@localhost>"
license="GPL-3.0-or-later"
homepage="https://openpaper.work/"
distfiles="https://github.com/openpaperwork/paperwork/archive/${version}.tar.gz"
checksum=8a1c7340e09346b43634ef75e9cf90c795e664d6bc40452cd4d8afd91e2ffbea

do_install() {
	make STRIP=true PREFIX=/usr DESTDIR=${DESTDIR} PIP_ARGS="--root=${DESTDIR}" -C paperwork-backend install
	make STRIP=true PREFIX=/usr DESTDIR=${DESTDIR} PIP_ARGS="--root=${DESTDIR}" -C paperwork-gtk install
	vinstall paperwork-gtk/data/paperwork_halo.svg 644 usr/share/icons/hicolor/scalable/apps paperwork.svg
}

````
