### ISSUE TITLE
Package Request: CoolProp

### ISSUE THREAD

**Issue by non-Jedi** [voidlinux/void-packages#12216]
The naive approach to using http://www.coolprop.org/ can end up with multiple
versions of the library installed around your system with the various wrappers.
It would be nice to have the shared libraries available at the OS level.

**Comment by non-Jedi** [comment]
See http://www.coolprop.org/coolprop/wrappers/SharedLibrary/index.html#linux-osx
for build instructions and
http://www.coolprop.org/coolprop/wrappers/index.html#common-wrapper-prerequisites
for build dependencies.

**Comment by cr6git** [comment]
What is this license? https://github.com/CoolProp/CoolProp/blob/master/LICENSE

**Comment by non-Jedi** [comment]
looks like MIT, right? https://opensource.org/licenses/MIT

**Comment by cr6git** [comment]
Created this template:
````
# Template file for 'CoolProp'
pkgname=CoolProp
version=6.1.0
revision=1
build_style=cmake
configure_args="-DCOOLPROP_SHARED_LIBRARY=ON"
hostmakedepends="python-pip python-six p7zip"
makedepends="python-devel"
short_desc="Thermophysical property database"
maintainer="local <root@localhost>"
homepage="http://www.coolprop.org"
license="MIT"
distfiles="https://github.com/CoolProp/CoolProp/archive/v${version}.tar.gz"
checksum=a9c405ce3fc1e91b4a43e48d53e8b7ef6b326ff5d9486f40d25c3cf531bf90fe

post_install() {
	vlicense LICENSE
}

````

Unfortunately, it doesn't work:
````
=> CoolProp-6.1.0_1: running do_build ...
Scanning dependencies of target generate_headers
Traceback (most recent call last):
  File "/builddir/CoolProp-6.1.0/dev/generate_headers.py", line 300, in <module>
    generate()
  File "/builddir/CoolProp-6.1.0/dev/generate_headers.py", line 285, in generate
    shutil.copy2(os.path.join(repo_root_path, 'externals','Catch','single_include','catch.hpp'),os.path.join(repo_root_path,'include','catch.hpp'))
  File "/usr/lib/python2.7/shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/builddir/CoolProp-6.1.0/externals/Catch/single_include/catch.hpp'
make[2]: *** [CMakeFiles/generate_headers.dir/build.make:57: CMakeFiles/generate_headers] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/generate_headers.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
=> ERROR: CoolProp-6.1.0_1: failed to run do_build() at line 49.
````

**Comment by Johnnynator** [comment]
@cr6git the project uses git submodules which aren't included in githubs automatic generated tarballs.

**Comment by cr6git** [comment]
@Johnnynator ah. you mean something like what we did with [#10070](https://github.com/voidlinux/void-packages/pull/10070) ?

**Comment by Johnnynator** [comment]
Yep.

**Comment by cr6git** [comment]
but I have no idea what to include in the template...
