### ISSUE TITLE
supercollider 3.9.1 won't launch

### ISSUE THREAD

**Issue by jarbowski** [voidlinux/void-packages#12328]
### System
x86_64
* xuname:  
Void 4.14.22_2 x86_64 GenuineIntel uptodate rrrmFF

  *output of ``xuname`` (part of xtools)*
* package:  
supercollider 3.9.1
  *affected package(s) including the version*

### Actual behavior

*** Error in `scide': munmap_chunk(): invalid pointer: 0x000055f40ce560c0 ***

### Steps to reproduce the behavior
launch supercollider (scide)

**Comment by mvf** [comment]
Confirmed. Starting with 3.9.1, SuperCollider's heap is all messed up. `scide` dies trying to parse its configuration file at `$HOME/.config/SuperCollider/sc_ide_conf.yaml`:

```
Starting program: /usr/bin/scide 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe331f700 (LWP 4244)]
[New Thread 0x7fffe24d5700 (LWP 4245)]
*** Error in `/usr/bin/scide': munmap_chunk(): invalid pointer: 0x00005555559310c0 ***

Thread 1 "scide" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: そのようなファイルやディレクトリはありません.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff279effd in __GI_abort () at abort.c:90
#2  0x00007ffff27df9dd in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff28e5d78 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff27e606c in malloc_printerr (action=<optimized out>, str=0x7ffff28e5dd0 "munmap_chunk(): invalid pointer", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5425
#4  0x00007ffff317c345 in std::string::reserve(unsigned long) () from /usr/lib/libstdc++.so.6
#5  0x0000555555686e55 in std::string::push_back (__c=73 'I', this=0x7fffffffde70) at /usr/include/c++/7.3/bits/basic_string.h:4238
#6  std::string::operator+= (__c=73 'I', this=0x7fffffffde70) at /usr/include/c++/7.3/bits/basic_string.h:4089
#7  YAML::ScanScalar (INPUT=..., params=...) at /builddir/SuperCollider-Source/external_libraries/yaml-cpp/src/scanscalar.cpp:78
#8  0x0000555555688609 in YAML::Scanner::ScanPlainScalar (this=this@entry=0x55555598b010) at /builddir/SuperCollider-Source/external_libraries/yaml-cpp/src/scantoken.cpp:315
#9  0x0000555555689a66 in YAML::Scanner::ScanNextToken (this=this@entry=0x55555598b010) at /builddir/SuperCollider-Source/external_libraries/yaml-cpp/src/scanner.cpp:164
#10 0x0000555555689cf1 in YAML::Scanner::EnsureTokensInQueue (this=this@entry=0x55555598b010) at /builddir/SuperCollider-Source/external_libraries/yaml-cpp/src/scanner.cpp:73
#11 0x0000555555689f09 in YAML::Scanner::empty (this=<optimized out>) at /builddir/SuperCollider-Source/external_libraries/yaml-cpp/src/scanner.cpp:20
#12 YAML::Parser::ParseDirectives (this=this@entry=0x7fffffffe0d0) at /builddir/SuperCollider-Source/external_libraries/yaml-cpp/src/parser.cpp:47
#13 0x000055555568c565 in YAML::Parser::HandleNextDocument (this=this@entry=0x7fffffffe0d0, eventHandler=...) at /builddir/SuperCollider-Source/external_libraries/yaml-cpp/src/parser.cpp:33
#14 0x000055555568cbbe in YAML::Load (input=...) at /builddir/SuperCollider-Source/external_libraries/yaml-cpp/src/parse.cpp:25
#15 0x00005555555d4e38 in ScIDE::Settings::readSettings (device=..., map=...) at /builddir/SuperCollider-Source/editors/sc-ide/core/settings/serialization.cpp:175
#16 0x00007ffff3688cca in QConfFileSettingsPrivate::syncConfFile (this=this@entry=0x555555997b60, confFile=confFile@entry=0x7fffd4011f10) at io/qsettings.cpp:1467
#17 0x00007ffff36890be in QConfFileSettingsPrivate::sync (this=this@entry=0x555555997b60) at io/qsettings.cpp:1365
#18 0x00007ffff3689d01 in QConfFileSettingsPrivate::initAccess (this=0x555555997b60) at io/qsettings.cpp:961
#19 QConfFileSettingsPrivate::QConfFileSettingsPrivate (this=0x555555997b60, fileName=..., format=<optimized out>) at io/qsettings.cpp:1196
#20 0x00007ffff3689def in QSettingsPrivate::create (format=QSettings::CustomFormat1, fileName=...) at io/qsettings.cpp:306
#21 QSettings::QSettings (this=0x555555996170, fileName=..., format=QSettings::CustomFormat1, parent=0x55555595eba0) at io/qsettings.cpp:2623
#22 0x00005555555dc91c in ScIDE::Settings::Manager::Manager (this=0x55555595eba0, filename=..., parent=<optimized out>) at /builddir/SuperCollider-Source/editors/sc-ide/core/settings/manager.cpp:35
#23 0x00005555555a110d in ScIDE::Main::Main (this=0x555555996600) at /builddir/SuperCollider-Source/editors/sc-ide/core/main.cpp:219
#24 0x00005555555a29e5 in ScIDE::Main::instance () at /builddir/SuperCollider-Source/editors/sc-ide/core/main.hpp:76
#25 0x000055555559fc09 in main (argc=<optimized out>, argv=<optimized out>) at /builddir/SuperCollider-Source/editors/sc-ide/core/main.cpp:90
```
Deleting `$HOME/.config/SuperCollider` will get `scide` to start (once), but it will show the following error message:
```
Interpreter has crashed or stopped forcefully. [Exit code: 6]
```
This is because the `sclang` child process crashes with the following callstack:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f4c5ebf4ffd in __GI_abort () at abort.c:90
#2  0x00007f4c5ec359dd in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f4c5ed3bd78 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f4c5ec3c06c in malloc_printerr (action=<optimized out>, str=0x7f4c5ed386b9 "free(): invalid pointer", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5425
#4  0x00007f4c5ec3cb7e in _int_free (av=0x7f4c5ef6ec20 <main_arena>, p=0x55e3cb77cef0, have_lock=0) at malloc.c:4174
#5  0x00007f4c5f5d186a in std::string::_M_mutate(unsigned long, unsigned long, unsigned long) () from /usr/lib/libstdc++.so.6
#6  0x00007f4c5f5d1d7e in std::string::_M_replace_safe(unsigned long, unsigned long, char const*, unsigned long) () from /usr/lib/libstdc++.so.6
#7  0x000055e3cb35e12f in std::string::assign (__s=0x55e3cb4cad64 "sclang", this=<optimized out>) at /usr/include/c++/7.3/bits/basic_string.h:4314
#8  std::string::operator= (__s=0x55e3cb4cad64 "sclang", this=<optimized out>) at /usr/include/c++/7.3/bits/basic_string.h:3637
#9  SC_LanguageClient::SC_LanguageClient (this=0x55e3cc0b7ba0, name=0x55e3cb4cad64 "sclang") at /builddir/SuperCollider-Source/lang/LangSource/SC_LanguageClient.cpp:100
#10 0x000055e3cb2a984c in SC_TerminalClient::SC_TerminalClient (this=0x55e3cc0b7ba0, name=<optimized out>) at /builddir/SuperCollider-Source/lang/LangSource/SC_TerminalClient.cpp:77
#11 0x000055e3cb2b6a0f in QtCollider::LangClient::LangClient (this=0x55e3cc0b7b90, name=0x55e3cb4cad64 "sclang") at /builddir/SuperCollider-Source/QtCollider/LanguageClient.cpp:38
#12 0x000055e3cb2a69fb in createLanguageClient (name=0x55e3cb4cad64 "sclang") at /builddir/SuperCollider-Source/lang/LangSource/SC_TerminalClient.cpp:719
#13 0x000055e3cb297d51 in main (argc=3, argv=0x7ffce0664c48) at /builddir/SuperCollider-Source/lang/LangSource/cmdLineFuncs.cpp:25
```

**Comment by pullmoll** [comment]
Does supercollider-3.9.1_2 solve the problem?

**Comment by jarbowski** [comment]
No, still the same issue:

*** Error in `scide': munmap_chunk(): invalid pointer: 0x0000561fd42790c0 ***

**Comment by mvf** [comment]
This also occurs in our previous version 3.8.0 when built in the current environment. I also tried rebuilding both `qt5` and `qt5-webkit` and linking/running with that, but to no avail. Linking against our shared `yaml-cpp` avoids the startup crash for `scide` but `sclang` still dies. The `x86_64-musl` version (#12726) seems to work and could be used in a chroot as a workaround.

This doesn't seem to be a heap issue after all. The application C++ code looks innocent and the first invalid heap access in `sclang` is the address of a data symbol being passed to `operator delete` when copy-assigning into a default-constructed `std::string` (where there should be nothing to `delete`):

```
==1122== Memcheck, a memory error detector
==1122== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==1122== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==1122== Command: sclang
==1122== 
==1122== Invalid free() / delete / delete[] / realloc()
==1122==    at 0x4C2E2BB: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1122==    by 0xBC67869: std::string::_M_mutate(unsigned long, unsigned long, unsigned long) (in /usr/lib/libstdc++.so.6.0.24)
==1122==    by 0xBC67D7D: std::string::_M_replace_safe(unsigned long, unsigned long, char const*, unsigned long) (in /usr/lib/libstdc++.so.6.0.24)
==1122==    by 0x23351E: assign (basic_string.h:4314)
==1122==    by 0x23351E: operator= (basic_string.h:3637)
==1122==    by 0x23351E: SC_LanguageClient::SC_LanguageClient(char const*) (SC_LanguageClient.cpp:100)
==1122==    by 0x18111B: SC_TerminalClient::SC_TerminalClient(char const*) (SC_TerminalClient.cpp:77)
==1122==    by 0x18C2BE: QtCollider::LangClient::LangClient(char const*) (LanguageClient.cpp:38)
==1122==    by 0x17E83A: createLanguageClient(char const*) (SC_TerminalClient.cpp:719)
==1122==    by 0x16F920: main (cmdLineFuncs.cpp:25)
==1122==  Address 0x5e97a0 is 0 bytes inside data symbol "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_empty_rep_storage@@Qt_5"
```

**Comment by mvf** [comment]
`stellarium` now seems to have the same issue: #13161

**Comment by jarbowski** [comment]
Does supercollider 3.9.3 fix the issue?

**Comment by mvf** [comment]
No, but that's not surprising since it's not an issue with SuperCollider. The good news: See [my latest comment](https://github.com/voidlinux/void-packages/issues/13161#issuecomment-385251988) in the Stellarium ticket for a workaround.
