### ISSUE TITLE
stellarium 0.17.0 does not start

### ISSUE THREAD

**Issue by wine** [voidlinux/void-packages#13161]
### System

* xuname:  
  `Void 4.15.12_1 x86_64 AuthenticAMD uptodate r`
* package:  
  `stellarium-0.17.0_1`

### Actual behavior
```
...
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.3 (standard edition)"
Loaded 90416 DSO records
Loading DSO outline data ...
Loaded 63 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
*** Error in `stellarium': free(): invalid pointer: 0x000055ccd11362e0 ***
Aborted
```
The pointer is different each time.

### Workaround
`stellarium-0.16.1_1` works correctly.
`xdowngrade /var/cache/xbps/stellarium-0.16.1_1.x86_64.xbps`

**Comment by Hoshpak** [comment]
Which graphics card and driver are you using? It works fine on my system with Intel integrated Graphics (Haswell) and the i915 driver.

**Comment by wine** [comment]
The graphic card is AMD Radeon R7 (Kaveri) with the `radeon` (xf86-video-ati-18.0.1_1) driver.

**Comment by mvf** [comment]
Same issue as #12328, **please don't open an upstream ticket**. Qt5 app dies when calling `operator=(char const *)` on a default-constructed `std::string` whose internal pointer points to data instead of to the heap.

Memcheck output:
```
==2634== Invalid free() / delete / delete[] / realloc()
==2634==    at 0x4C2E2BB: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2634==    by 0x7EBF869: std::string::_M_mutate(unsigned long, unsigned long, unsigned long) (in /usr/lib/libstdc++.so.6.0.24)
==2634==    by 0x7EBFD7D: std::string::_M_replace_safe(unsigned long, unsigned long, char const*, unsigned long) (in /usr/lib/libstdc++.so.6.0.24)
==2634==    by 0x8B3203: assign (basic_string.h:4314)
==2634==    by 0x8B3203: operator= (basic_string.h:3637)
==2634==    by 0x8B3203: gSatTEME::gSatTEME(char const*, char*, char*) (gSatTEME.cpp:67)
==2634==    by 0x8B13E4: gSatWrapper::gSatWrapper(QString, QString, QString) (gSatWrapper.cpp:61)
==2634==    by 0x87E729: Satellite::setNewTleElements(QString const&, QString const&) (Satellite.cpp:754)
==2634==    by 0x883641: Satellite::Satellite(QString const&, QMap<QString, QVariant> const&) (Satellite.cpp:162)
==2634==    by 0x88FCA8: Satellites::setDataMap(QMap<QString, QVariant> const&) (Satellites.cpp:825)
==2634==    by 0x893979: Satellites::loadCatalog() (Satellites.cpp:723)
==2634==    by 0x894569: Satellites::init() (Satellites.cpp:192)
==2634==    by 0x499DA0: StelApp::initPlugIns() (StelApp.cpp:623)
==2634==    by 0x3111F8: StelMainView::init() (StelMainView.cpp:841)
==2634==  Address 0x11862e0 is 0 bytes inside data symbol "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_empty_rep_storage@@Qt_5"
```
Backtrace:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff4166ffd in __GI_abort () at abort.c:90
#2  0x00007ffff41a79dd in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff42add78 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff41ae06c in malloc_printerr (action=<optimized out>, str=0x7ffff42aa6b9 "free(): invalid pointer", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5425
#4  0x00007ffff41aeb7e in _int_free (av=0x7ffff44e0c20 <main_arena>, p=0x5555565d22d0, have_lock=0) at malloc.c:4174
#5  0x00007ffff4b4386a in std::string::_M_mutate(unsigned long, unsigned long, unsigned long) () from /usr/lib/libstdc++.so.6
#6  0x00007ffff4b43d7e in std::string::_M_replace_safe(unsigned long, unsigned long, char const*, unsigned long) () from /usr/lib/libstdc++.so.6
#7  0x0000555555cff204 in std::string::assign (__s=0x555560c065d8 "00694", this=0x555556840680) at /usr/include/c++/7.3/bits/basic_string.h:4314
#8  std::string::operator= (__s=0x555560c065d8 "00694", this=0x555556840680) at /usr/include/c++/7.3/bits/basic_string.h:3637
#9  gSatTEME::gSatTEME (this=0x555556840330, pstrName=0x555560c065d8 "00694", pstrTleLine1=0x555560f602a8 "1 00694U 63047A   17352.63392357  .00000407  00000-0  38135-4 0  9990", pstrTleLine2=0x555560c0a288 "2 00694  30.3568 230.0006 0587301 191.8720 166.7473 14.02243439709001") at /builddir/stellarium-0.17.0/plugins/Satellites/src/gsatellite/gSatTEME.cpp:67
#10 0x0000555555cfd3e5 in gSatWrapper::gSatWrapper (this=0x55556101c2f0, designation=..., tle1=..., tle2=...) at /builddir/stellarium-0.17.0/plugins/Satellites/src/gSatWrapper.cpp:61
#11 0x0000555555cca72a in Satellite::setNewTleElements (this=this@entry=0x55556059c910, tle1=..., tle2=...) at /builddir/stellarium-0.17.0/plugins/Satellites/src/Satellite.cpp:754
#12 0x0000555555ccf642 in Satellite::Satellite (this=0x55556059c910, identifier=..., map=...) at /builddir/stellarium-0.17.0/plugins/Satellites/src/Satellite.cpp:162
#13 0x0000555555cdbca9 in Satellites::setDataMap (this=this@entry=0x55555fea3e40, map=...) at /builddir/stellarium-0.17.0/plugins/Satellites/src/Satellites.cpp:825
#14 0x0000555555cdf97a in Satellites::loadCatalog (this=this@entry=0x55555fea3e40) at /builddir/stellarium-0.17.0/plugins/Satellites/src/Satellites.cpp:723
#15 0x0000555555ce056a in Satellites::init (this=0x55555fea3e40) at /builddir/stellarium-0.17.0/plugins/Satellites/src/Satellites.cpp:192
#16 0x00005555558e5da1 in StelApp::initPlugIns (this=0x555556883550) at /builddir/stellarium-0.17.0/src/core/StelApp.cpp:623
#17 0x000055555575d1f9 in StelMainView::init (this=0x7fffffffe600) at /builddir/stellarium-0.17.0/src/StelMainView.cpp:841
#18 0x000055555576071e in StelGLWidget::initializeGL (this=0x5555569187e0) at /builddir/stellarium-0.17.0/src/StelMainView.cpp:144
#19 0x00007ffff6e7ca55 in QOpenGLWidgetPrivate::initialize (this=this@entry=0x555556858250) at kernel/qopenglwidget.cpp:852
#20 0x00007ffff6e7d768 in QOpenGLWidget::event (this=0x5555569187e0, e=0x7fffffffe260) at kernel/qopenglwidget.cpp:1442
#21 0x00007ffff6e1d6cc in QApplicationPrivate::notify_helper (this=this@entry=0x55555663b940, receiver=receiver@entry=0x5555569187e0, e=e@entry=0x7fffffffe260) at kernel/qapplication.cpp:3732
#22 0x00007ffff6e24e84 in QApplication::notify (this=0x7fffffffe570, receiver=0x5555569187e0, e=0x7fffffffe260) at kernel/qapplication.cpp:3491
#23 0x00007ffff50ed5d8 in QCoreApplication::notifyInternal2 (receiver=receiver@entry=0x5555569187e0, event=event@entry=0x7fffffffe260) at kernel/qcoreapplication.cpp:1050
#24 0x00007ffff6e58de8 in QCoreApplication::sendEvent (event=0x7fffffffe260, receiver=0x5555569187e0) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#25 QWidgetPrivate::show_helper (this=this@entry=0x555556858250) at kernel/qwidget.cpp:8035
#26 0x00007ffff6e5bf1b in QWidget::setVisible (this=0x5555569187e0, visible=<optimized out>) at kernel/qwidget.cpp:8331
#27 0x00007ffff6e58d10 in QWidgetPrivate::showChildren (this=this@entry=0x55555690ef10, spontaneous=spontaneous@entry=false) at kernel/qwidget.cpp:8414
#28 0x00007ffff6e58dbf in QWidgetPrivate::show_helper (this=this@entry=0x55555690ef10) at kernel/qwidget.cpp:7982
#29 0x00007ffff6e5bf1b in QWidget::setVisible (this=0x7fffffffe600, visible=<optimized out>) at kernel/qwidget.cpp:8331
#30 0x0000555555738808 in main (argc=<optimized out>, argv=<optimized out>) at /builddir/stellarium-0.17.0/src/main.cpp:369
```
Based on the other issue, I would expect that the:
- old version won't work either if rebuilt in the current environment (@wine Better hold on to those old binaries)
- `x86_64-musl` version works (@Hoshpak Are you running musl by any chance?)

**Comment by Hoshpak** [comment]
@mvf I'm running glibc.

**Comment by wine** [comment]
The latest `stellarium-0.18.0_1` is also affected. I think @mvf is right, it doesn't seem to be a Stellarium specific issue.

**Comment by mvf** [comment]
@Hoshpak Okay, then you're still running `0.16.1`. As expected, `0.18.0` crashes as well.

**Comment by Hoshpak** [comment]
@mvf negative, I just updated:
```
 -------------------------------------------------------
[ This is Stellarium 0.18.0 - http://www.stellarium.org ]
[ Copyright (C) 2000-2018 Fabien Chereau et al.         ]
 -------------------------------------------------------
```

**Comment by Hoshpak** [comment]
I think I could narrow the issue down to the "Satellites" plugin. If I disable loading of the plugin in the "plugins_load_at_startup" section in ~/.stellarium/config.ini, the application runs again without crashing.

**Comment by wine** [comment]
Unfortunately, on my system Stellarium still crashes with the Satellites plugin (and/or the others) set to false. Editing the config.ini file by trial and error, the startup process went a little further. But in the end:
```
...
stel.OpenGLArray: Vertex Array Objects are supported
Initializing basic GL shaders... 
Creating GUI ...
*** Error in `stellarium': free(): invalid pointer: 0x000055cc20b22300 ***
Aborted
```
It's evident that there is a problem in the environment in which Stellarium runs.

**Comment by mvf** [comment]
I think I know what the issue is, but I don't know yet how to fix it.

When a `std::string` is default-constructed or emptied, its data pointer references a statically allocated empty representation, `_S_empty_rep_storage`. This avoids allocation or `nullptr` checks all over the place. When a string gets replaced like in our case, its old data needs to be taken care of. For that, the pointer is compared against the address of the empty representation. If it differs, the string has allocated and its data needs to be `delete`d.

Our problem seems to be that there are multiple `_S_empty_rep_storage` symbol versions, i.e. a `GLIBCXX_3.4` and a `Qt5` version, with different addresses. Inlined code like `std::string`'s default ctor sees the `Qt5` version and code on the `libstdc++` side sees the `GLIBCXX_3.4` version. So if the latter is asked to destroy an empty string that was initialized via the former, it thinks the string's data is heap-allocated and passes that pointer to `delete`, causing the crash. This also explains why moving the crashing code to its own shared library (that is not built against Qt5) works around the issue, as seen in the `scide` case.

**Comment by mvf** [comment]
Quick update, I hacked a tool that attempts to "repair" binaries affected by this problem. There's no 100% guarantee that this will fix everything, but `stellarium` and `sclang` are now starting again over here.

To try this, fetch the C source from [this Gist](https://gist.github.com/mvf/1c0efaa932ba8516be113bb0b14da67b) and:
```
$ make void-qt5-anticrash
$ ./void-qt5-anticrash sclang stellarium ...
```
All files passed as arguments are patched in place, simply removing versioning from the offending data symbol. Since the evil `Qt_5` symbol is weak, the proper one from `libstdc++` then takes precedence, fixing the crash.

**Comment by wine** [comment]
@mvf Your knowledge is impressive, congratulations. I patched the latest `0.18.0` binary with your tool and it worked, of course. Thank you for your work.

However the underlying problem is still here, so I don't close the issue for now.
