### ISSUE TITLE
ImageMagick converting PDF to PNG crashes on glibc

### ISSUE THREAD

**Issue by codebam** [voidlinux/void-packages#13303]
### System

* xuname:  
  Void 4.16.0+ x86_64 GenuineIntel uptodate rrFFFF
* package:  
  ImageMagick-6.9.9.40_1

### Expected behavior
ImageMagick should convert the PDF to a PNG successfully

### Actual behavior
ImageMagick aborts without an error message and is unsuccessful

### Steps to reproduce the behavior
Download any PDF file

```
$ convert pdf.pdf pdf.png
[1]    19963 abort      convert pdf.pdf pdf.png
$ 
```

**Comment by jnbr** [comment]
Backtrace:
```
Starting program: /usr/bin/convert test.pdf test.png
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x1010) at malloc.c:3123
3123    malloc.c: No such file or directory.
(gdb) backtrace
#0  __GI___libc_free (mem=0x1010) at malloc.c:3123
#1  0x00007ffff6dae8a5 in cmsCloseProfile () from /usr/lib/liblcms2.so.2
#2  0x00007fffef5de962 in rc_free_icc_profile (mem=<optimized out>, ptr_in=0x5555559409a0, cname=<optimized out>) at ./base/gsicc_manage.c:1980
#3  0x00007fffef7dba75 in gs_cspace_final (cmem=<optimized out>, vptr=0x555555847340) at ./base/gscspace.c:99
#4  0x00007fffef8db152 in restore_finalize (mem=mem@entry=0x5555557d0fb8) at ./psi/isave.c:952
#5  0x00007fffef8dc111 in alloc_restore_all (i_ctx_p=i_ctx_p@entry=0x555555861f20) at ./psi/isave.c:893
#6  0x00007fffef89a1e3 in gs_main_finit (minst=0x5555557c50f0, exit_status=exit_status@entry=0, code=code@entry=0) at ./psi/imain.c:989
#7  0x00007fffef89a441 in gs_to_exit_with_code (mem=<optimized out>, exit_status=exit_status@entry=0, code=code@entry=0) at ./psi/imain.c:1026
#8  0x00007fffef89a457 in gs_to_exit (mem=<optimized out>, exit_status=exit_status@entry=0) at ./psi/imain.c:1031
#9  0x00007fffef89df03 in gsapi_exit (instance=<optimized out>) at ./psi/iapi.c:564
#10 0x00007ffff08b41e3 in InvokePDFDelegate (exception=0x555555767f10, message=0x7fffffff57c0 "",
    command=0x7fffffff07c0 "'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72'  '-sOutpu"..., verbose=<optimized out>) at coders/pdf.c:263
#11 ReadPDFImage (image_info=0x555555778730, exception=0x555555767f10) at coders/pdf.c:778
#12 0x00007ffff797d32e in ReadImage (image_info=image_info@entry=0x555555774590, exception=exception@entry=0x555555767f10) at magick/constitute.c:551
#13 0x00007ffff797e3fb in ReadImages (image_info=image_info@entry=0x5555557703f0, exception=0x555555767f10) at magick/constitute.c:870
#14 0x00007ffff7609670 in ConvertImageCommand (image_info=0x5555557703f0, image_info@entry=0x55555576c250, argc=<optimized out>, argc@entry=3, argv=<optimized out>, argv@entry=0x7fffffffe458,
    metadata=metadata@entry=0x0, exception=exception@entry=0x555555767f10) at wand/convert.c:633
#15 0x00007ffff7671b64 in MagickCommandGenesis (image_info=0x55555576c250, command=0x7ffff76076a0 <ConvertImageCommand>, argc=3, argv=0x7fffffffe458, metadata=0x0, exception=0x555555767f10) at wand/mogrify.c:172
#16 0x00005555555548d9 in ConvertMain (argv=0x7fffffffe458, argc=3) at utilities/convert.c:81
#17 main (argc=3, argv=0x7fffffffe458) at utilities/convert.c:92
```

This only happens with `ghostscript-9.23_1`, it works fine with `ghostscript-9.22_1`.
