### ISSUE TITLE
youtube-dl  - no module _ssl

### ISSUE THREAD

**Issue by emacsomancer** [voidlinux/void-packages#13900]
### System

* xuname:  
Void 4.16.4_1 x86_64-musl GenuineIntel uptodate rFFF
* package:  
youtube-dl-2018.04.25_1

### Expected behavior
download videos
### Actual behavior
error, with output:
```
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 3, in <module>
    import youtube_dl
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 15, in <module>
    from .options import (
  File "/usr/lib/python2.7/site-packages/youtube_dl/options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
  File "/usr/lib/python2.7/site-packages/youtube_dl/downloader/__init__.py", line 3, in <module>
    from .common import FileDownloader
  File "/usr/lib/python2.7/site-packages/youtube_dl/downloader/common.py", line 10, in <module>
    from ..utils import (
  File "/usr/lib/python2.7/site-packages/youtube_dl/utils.py", line 29, in <module>
    import ssl
  File "/usr/lib/python2.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl
```

### Steps to reproduce the behavior
use `youtube-dl`

**Comment by beardyjay** [comment]
I have the same issue since I updated this morning. 

However, it seems to be affect anything that I try to run using python3. So I wonder if its a issue with the [latest python3 update](https://github.com/voidlinux/void-packages/commit/425bfff5130e0207ce0dce7e6ab31b7004c8f33f) instead of the youtube-dl update.

**Comment by tsudoko** [comment]
Can reproduce, happens with Python 3 as well.
```
~ $ python3 -c 'import ssl'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
~ $ python2 -c 'import ssl'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl
```
