### ISSUE TITLE
python-Cython build fails

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#14115]
Trying to build `python-Cython-0.28.2_1` fails with the following messages:
```
running build_ext
Unable to find pgen, not compiling formal grammar.
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
Traceback (most recent call last):
  File "setup.py", line 285, in <module>
    **setup_args
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 973, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/builddir/Cython-0.28.2/Cython/Distutils/build_ext.py", line 21, in finalize_options
    self.distribution.ext_modules, nthreads=nthreads, force=self.force)
  File "/builddir/Cython-0.28.2/Cython/Build/Dependencies.py", line 897, in cythonize
    aliases=aliases)
  File "/builddir/Cython-0.28.2/Cython/Build/Dependencies.py", line 735, in create_extension_list
    Extension_distutils = sys.modules['setuptools.extension']._Extension
KeyError: 'setuptools.extension'
=> ERROR: python-Cython-0.28.2_1: do_install: 'python${pyver} setup.py build --build-base=build-${pyver} install --prefix=/usr --root=${DESTDIR} ${make_install_args}' exited with 1
=> ERROR:   in do_install() at common/build-style/python-module.sh:49
```

It seems as if `python-Cython` is incompatible with the current `python{,3}-setuptools`?

**Comment by asergi** [comment]
```
=> Registering python3-Cython-0.28.2_1.x86_64.xbps into /host/binpkgs ...
index: added `python3-Cython-0.28.2_1' (x86_64).
```

**Comment by pullmoll** [comment]
Strange enough all of a sudden it worked for me as well...
Closing for it seems to be a non-issue :p
