### ISSUE TITLE
Missing symbols in libArcus

### ISSUE THREAD

**Issue by Gigahawk** [voidlinux/void-packages#14485]
### System

* xuname:  
  Void 4.16.7_1 x86_64 GenuineIntel uptodate rrm
* package:  
  - cura
  - cura-engine
  - libArcus
  - protobuf (?)

### Expected behavior
Both Cura and CuraEngine should run when called from the terminal.

### Actual behavior
After updating Cura (#13873) CuraEngine crashes with 
```
CuraEngine: symbol lookup error: /usr/lib/libArcus.so.3: undefined symbol: _ZN6google8protobuf2io16CodedInputStream18SetTotalBytesLimitEii
```
Recompiling libArcus from the Ultimaker repo fixes this but then Cura will crash with
```
Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.6/site-packages/cura/CrashHandler.py", line 21, in <module>
    from UM.Application import Application
  File "/usr/lib/python3.6/site-packages/UM/Application.py", line 9, in <module>
    from UM.Controller import Controller
  File "/usr/lib/python3.6/site-packages/UM/Controller.py", line 10, in <module>
    from UM.View.View import View
  File "/usr/lib/python3.6/site-packages/UM/View/View.py", line 4, in <module>
    from UM.View.Renderer import Renderer
  File "/usr/lib/python3.6/site-packages/UM/View/Renderer.py", line 6, in <module>
    from UM.View.RenderPass import RenderPass #For typing.
  File "/usr/lib/python3.6/site-packages/UM/View/RenderPass.py", line 7, in <module>
    import UM.Qt.QtApplication
  File "/usr/lib/python3.6/site-packages/UM/Qt/QtApplication.py", line 19, in <module>
    from UM.Application import Application
ImportError: cannot import name 'Application'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/cura", line 131, in <module>
    import Arcus #@UnusedImport
ImportError: /usr/lib/libArcus.so.3: undefined symbol: _ZN6google8protobuf2io16CodedInputStream18SetTotalBytesLimitEi
```

### Steps to reproduce the behavior
1. Update Cura/CuraEngine to 3.3 (#13873)
2. Attempt to run CuraEngine
3. Manually install [libArcus](https://github.com/Ultimaker/libArcus), (I had to manually copy it to `/usr/lib`)
4. Attempt to run Cura

**Comment by Gigahawk** [comment]
Sorry, it seems that `make` and `xbps-install` install cura and its related libraries to different folders and that was causing the issue.
