### ISSUE TITLE
ipython3 crashed

### ISSUE THREAD

**Issue by 230v** [voidlinux/void-packages#1570]
$ ipython3 qtconsole
Traceback (most recent call last):
  File "/bin/ipython3", line 5, in <module>
    start_ipython()
  File "/usr/lib/python3.4/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/config/application.py", line 573, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 320, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/core/application.py", line 369, in initialize
    self.parse_command_line(argv)
  File "/usr/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 315, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/usr/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/config/application.py", line 471, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/usr/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/config/application.py", line 409, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/qt/console/qtconsoleapp.py", line 358, in initialize
    super(IPythonQtConsoleApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/core/application.py", line 375, in initialize
    self.init_profile_dir()
  File "/usr/lib/python3.4/site-packages/IPython/core/application.py", line 282, in init_profile_dir
    p = ProfileDir.find_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
  File "/usr/lib/python3.4/site-packages/IPython/core/profiledir.py", line 230, in find_profile_dir_by_name
    return cls(location=profile_dir, config=config)
  File "/usr/lib/python3.4/site-packages/IPython/config/configurable.py", line 86, in __init__
    super(Configurable, self).__init__(**kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 565, in __init__
    setattr(self, key, value)
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 445, in __set__
    obj._notify_trait(self.name, old_value, new_value)
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 602, in _notify_trait
    c(name, old_value, new_value)
  File "/usr/lib/python3.4/site-packages/IPython/core/profiledir.py", line 68, in _location_changed
    self.check_dirs()
  File "/usr/lib/python3.4/site-packages/IPython/core/profiledir.py", line 159, in check_dirs
    self.check_static_dir()
  File "/usr/lib/python3.4/site-packages/IPython/core/profiledir.py", line 144, in check_static_dir
    from IPython.html import DEFAULT_STATIC_FILES_PATH
ImportError: No module named 'IPython.html'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

**Comment by asergi** [comment]
https://github.com/voidlinux/void-packages/commit/bc66ad89c836c8da9521416ffb4013a353c51607
