### ISSUE TITLE
arduino is broken

### ISSUE THREAD

**Issue by abuibrahim** [voidlinux/void-packages#2376]
$ arduino 
Picked up JAVA_TOOL_OPTIONS: 
java.io.FileNotFoundException: /usr/lib/arduino/dist/package_index.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at processing.app.helpers.FileUtils.copyFile(FileUtils.java:46)
	at processing.app.BaseNoGui.initPackages(BaseNoGui.java:609)
	at processing.app.Base.<init>(Base.java:299)
	at processing.app.Base.guardedMain(Base.java:226)
	at processing.app.Base.main(Base.java:137)
$

**Comment by Gottox** [comment]
narf. typo. 2b6d70a23e4e532986a12837d2b3976b02301d59
