### ISSUE TITLE
python-m2crypto pkg broken

### ISSUE THREAD

**Issue by radare** [voidlinux/void-packages#2935]
``` 
$ sudo xbps-install python-M2Crypto
$ python
>>> import M2Crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/M2Crypto/__init__.py", line 22, in <module>
    import _m2crypto
  File "/usr/lib/python2.7/site-packages/M2Crypto/_m2crypto.py", line 28, in <module>
    __m2crypto = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/M2Crypto/_m2crypto.py", line 24, in swig_import_helper
    _mod = imp.load_module('__m2crypto', fp, pathname, description)
ImportError: /usr/lib/python2.7/site-packages/M2Crypto/__m2crypto.so: undefined symbol: SSLv2_method

```

**Comment by xtraeme** [comment]
Assigned to maintainer.

**Comment by radare** [comment]
That was really quick! Thanks it works!
