### ISSUE TITLE
fastd: broken

### ISSUE THREAD

**Issue by Gottox** [voidlinux/void-packages#3201]
I recently updated my fastd instances and noticed, that the client exits with "Illegal Instruction". I tried to debug the issue and fixed at least one issue (I still do not understand why this [patch](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/fastd/patches/fix-segfault.patch) actually fixes anything)

Anyway, here's the gdb output:
```
[root@storage1 fastd]# gdb --args fastd --config /etc/fastd/fastd.conf
GNU gdb (GDB) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from fastd...Reading symbols from /usr/lib/debug//usr/bin/fastd...done.
done.
(gdb) run
Starting program: /usr/bin/fastd --config /etc/fastd/fastd.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
2015-12-20 11:54:48 +0100 --- Info: fastd v17 starting
2015-12-20 11:54:48 +0100 --- DEBUG: initializing tun/tap device...
2015-12-20 11:54:48 +0100 --- DEBUG: tun/tap device initialized.
2015-12-20 11:54:48 +0100 --- Verbose: dropped capabilities
2015-12-20 11:54:48 +0100 --- Verbose: adding peer <pi1>
2015-12-20 11:54:48 +0100 --- Verbose: resolving host `91.59.80.230' for peer <pi1>...
[New Thread 0x7ffff6f9d700 (LWP 7659)]
2015-12-20 11:54:48 +0100 --- Verbose: resolved host `91.59.80.230' successfully
[Thread 0x7ffff6f9d700 (LWP 7659) exited]
2015-12-20 11:54:48 +0100 --- DEBUG: resetting socket for peer <pi1>
2015-12-20 11:54:48 +0100 --- DEBUG: generating new handshake key
2015-12-20 11:54:48 +0100 --- Verbose: sending handshake to <pi1>[91.59.80.230:10000]...
2015-12-20 11:54:48 +0100 --- DEBUG: learned new local MAC address 92:05:90:53:8e:88
2015-12-20 11:54:48 +0100 --- Verbose: received handshake response from <pi1>[91.59.80.230:10000] using fastd v17
2015-12-20 11:54:48 +0100 --- DEBUG: finishing handshake with <pi1>[91.59.80.230:10000]...
2015-12-20 11:54:48 +0100 --- Verbose: 91.59.80.230:10000 authorized as <pi1>

Program received signal SIGILL, Illegal instruction.
0x000055555557ac32 in _mm_shuffle_epi8 (__Y=..., __X=...) at /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9/include/tmmintrin.h:138
138	/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9/include/tmmintrin.h: No such file or directory.
(gdb) bt full
#0  0x000055555557ac32 in _mm_shuffle_epi8 (__Y=..., __X=...) at /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9/include/tmmintrin.h:138
No locals.
#1  byteswap (v=...) at /builddir/fastd-17/src/crypto/mac/ghash/pclmulqdq/ghash_pclmulqdq_impl.c:76
No locals.
#2  fastd_ghash_pclmulqdq_init (key=0x7fffffffd950 "c\202\242\061\204\030\315T\313m\034ڌ=m\302\063\334u.H\227C\201")
    at /builddir/fastd-17/src/crypto/mac/ghash/pclmulqdq/ghash_pclmulqdq_impl.c:85
No locals.
#3  0x0000555555575cee in method_session_init (method=0x55555578aeb0, secret=0x7fffffffd9b0 "\216\267\027\034'", initiator=<optimized out>)
    at /builddir/fastd-17/src/methods/generic_gmac/generic_gmac.c:133
        zeroblock = {b = '\000' <repeats 15 times>, dw = {0, 0, 0, 0}, qw = {0, 0}}
        H = {b = "c\202\242\061\204\030\315T\313m\034ڌ=", <incomplete sequence \302>, dw = {832733795, 1422727300, 3659296203, 3261939084}, qw = {6110567225459114595, 
            14009921690983493067}}
        iv_length = <optimized out>
        zeroiv = 0x7fffffffd940 ""
#4  0x000055555555be24 in new_session (serial=1, salt=0x7fffffffdbc0, sigma=0x7fffffffdba0, Y=0x55555579de30, X=0x55555578b040, B=<optimized out>, A=<optimized out>, 
    initiator=true, method=0x55555578b2a0, peer=0x55555578a8f0) at /builddir/fastd-17/src/protocols/ec25519_fhmqvc/handshake.c:111
        secret = 0x7fffffffd9b0
#5  establish (peer=peer@entry=0x55555578a8f0, method=method@entry=0x55555578b2a0, sock=sock@entry=0x55555578ae30, local_addr=local_addr@entry=0x7fffffffdff0, 
    remote_addr=remote_addr@entry=0x7fffffffe010, initiator=initiator@entry=true, A=0x55555578ab30, B=0x7fffffffdb80, X=0x55555578b040, Y=0x55555579de30, 
    sigma=0x7fffffffdba0, salt=0x7fffffffdbc0, serial=1) at /builddir/fastd-17/src/protocols/ec25519_fhmqvc/handshake.c:153
No locals.
#6  0x0000555555572294 in finish_handshake (method=0x55555578b2a0, handshake=0x7fffffffdcf0, peer_handshake_key=0x7fffffffdb80, handshake_key=0x55555578aaf8, 
    peer=0x55555578a8f0, remote_addr=0x7fffffffe010, local_addr=0x7fffffffdff0, sock=0x55555578ae30) at /builddir/fastd-17/src/protocols/ec25519_fhmqvc/handshake.c:368
        compat = false
        sigma = {int256 = {p = "R\337\t\336\036s\250\327\337O\336\017\227Ib\354\245/\336\364\316Ѐ\335l\235M\331\341\020\243\t"}, u32 = {3725188946, 3618140958, 
            266227679, 3965864343, 4108201893, 3716206798, 3645742444, 161681633}, 
          u8 = "R\337\t\336\036s\250\327\337O\336\017\227Ib\354\245/\336\364\316Ѐ\335l\235M\331\341\020\243\t"}
        buffer = {buffer = {base = 0x55555578af40, base_len = 140737340761728, data = 0x55555557d430, len = 93824994538048}, little_endian = 176}
        shared_handshake_key = {w = {2222100934, 193316646, 3240390481, 1135018789, 1580703420, 3453548692, 1601357648, 3061592858}, 
          b = "Ƒr\204&ǅ\vQo$\301%\003\247C\274\236\067^\224\370\330\315P\307r_\032\063|\266"}
        shared_handshake_key_compat = {w = {1434005984, 21845, 0, 0, 4294958144, 32767, 2, 0}, 
          b = "\340\061yUUU\000\000\000\000\000\000\000\000\000\000@\334\377\377\377\177\000\000\002\000\000\000\000\000\000"}
        valid = <optimized out>
#7  fastd_protocol_ec25519_fhmqvc_handshake_handle (sock=0x55555578ae30, local_addr=0x7fffffffdff0, remote_addr=0x7fffffffe010, peer=0x55555578a8f0, 
    handshake=0x7fffffffdcf0) at /builddir/fastd-17/src/protocols/ec25519_fhmqvc/handshake.c:747
        method = 0x55555578b2a0
        peer_handshake_key = {int256 = {p = ")\354\063\065ҧ\310\"ʜ\357\332\002\255\336\324He\232\337\060c\367\271\352l\270s\006\325\354e"}, u32 = {892595241, 
            583575506, 3673136330, 3571363074, 3751437640, 3119997744, 1941466346, 1710019846}, 
          u8 = ")\354\063\065ҧ\310\"ʜ\357\332\002\255\336\324He\232\337\060c\367\271\352l\270s\006\325\354e"}
        handshake_key = 0x55555578aaf8
#8  0x0000555555560461 in fastd_handshake_handle (sock=sock@entry=0x55555578ae30, local_addr=local_addr@entry=0x7fffffffdff0, 
    remote_addr=remote_addr@entry=0x7fffffffe010, peer=peer@entry=0x55555578a8f0, buffer=...) at /builddir/fastd-17/src/handshake.c:461
        peer_version = 0x55555578ae90 "v17"
        handshake = {type = 2 '\002', peer_version = 0x55555578ae90 "v17", records = {{length = 1, data = 0x55555579b930 "\002\004"}, {length = 1, 
---Type <return> to continue, or q <return> to quit---
              data = 0x55555579b96b ""}, {length = 0, data = 0x0}, {length = 0, data = 0x0}, {length = 1, data = 0x55555579b935 ""}, {length = 14, 
              data = 0x55555579b947 "ec25519-fhmqvc\016"}, {length = 32, 
              data = 0x55555579b970 "\253Ӹ\312\364sd&\356(\350i\266\177I\257Ɖ\312\310\031\253\301\251qaʬ\005\271\376e\a"}, {length = 32, 
              data = 0x55555579b994 "\272\311?h\021C?\275\321\337\347\224\065`/\362\063\334u.H\227C\201\377\037\006\001l\311Ϣ\b"}, {length = 32, 
              data = 0x55555579b9b8 ")\354\063\065ҧ\310\"ʜ\357\332\002\255\336\324He\232\337\060c\367\271\352l\270s\006\325\354e\t"}, {length = 32, 
              data = 0x55555579b9dc "\031\222\t'\363\251\237JҎy\205\237\364b\261\373\323\355lb\264b˞\030\336Sy>Xj\017"}, {length = 0, data = 0x0}, {length = 2, 
              data = 0x55555579b93a "\334\005\r"}, {length = 0, data = 0x0}, {length = 3, data = 0x55555579b940 "v17\005"}, {length = 14, 
              data = 0x55555579b959 "salsa2012+gmac\001"}, {length = 32, data = 0x55555579ba00 ""}}, tlv_len = 244, tlv_data = 0x55555579b92c, little_endian = true}
#9  0x000055555556740d in handle_socket_receive_known (buffer=..., peer=0x55555578a8f0, remote_addr=0x7fffffffe010, local_addr=0x7fffffffdff0, sock=0x55555578ae30)
    at /builddir/fastd-17/src/receive.c:188
        packet_type = 0x55555579b928 "\001"
#10 handle_socket_receive (buffer=..., remote_addr=0x7fffffffe010, local_addr=0x7fffffffdff0, sock=0x55555578ae30) at /builddir/fastd-17/src/receive.c:234
        peer = 0x55555578a8f0
#11 fastd_receive (sock=0x55555578ae30) at /builddir/fastd-17/src/receive.c:286
        max_len = <optimized out>
        buffer = {base = 0x55555579b920, base_len = 1577, data = 0x55555579b928, len = <optimized out>}
        local_addr = {sa = {sa_family = 2, sa_data = "\241\375\300\250\001\300\000\000\000\000\000\000\000"}, in = {sin_family = 2, sin_port = 64929, sin_addr = {
              s_addr = 3221334208}, sin_zero = "\000\000\000\000\000\000\000"}, in6 = {sin6_family = 2, sin6_port = 64929, sin6_flowinfo = 3221334208, sin6_addr = {
              __in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}}
        recvaddr = {sa = {sa_family = 2, sa_data = "'\020[;P\346\000\000\000\000\000\000\000"}, in = {sin_family = 2, sin_port = 4135, sin_addr = {s_addr = 3864017755}, 
            sin_zero = "\000\000\000\000\000\000\000"}, in6 = {sin6_family = 2, sin6_port = 4135, sin6_flowinfo = 3864017755, sin6_addr = {__in6_u = {
                __u6_addr8 = '\000' <repeats 12 times>, "\330\000\000", __u6_addr16 = {0, 0, 0, 0, 0, 0, 216, 0}, __u6_addr32 = {0, 0, 0, 216}}}, sin6_scope_id = 3600}}
        buffer_vec = {iov_base = 0x55555579b928, iov_len = 1538}
        cbuf = "\034", '\000' <repeats 11 times>, "\b\000\000\000\002\000\000\000\300\250\001\300\300\250\001\300", '\000' <repeats 12 times>, "handshak", '\000' <repeats 312 times>...
        message = {msg_name = 0x7fffffffe010, msg_namelen = 16, msg_iov = 0x7fffffffdfc0, msg_iovlen = 1, msg_control = 0x7fffffffe0b0, msg_controllen = 32, 
          msg_flags = 0}
        len = <optimized out>
#12 0x0000555555566716 in fastd_poll_handle () at /builddir/fastd-17/src/poll.c:198
        sock = <optimized out>
        maintenance_timeout = <optimized out>
        timeout = <optimized out>
        events = {{events = 1, data = {ptr = 0x55555578ae30, fd = 1433972272, u32 = 1433972272, u64 = 93824994553392}}, {events = 21845, data = {ptr = 0xa6, fd = 166, 
              u32 = 166, u64 = 166}}, {events = 1431767351, data = {ptr = 0x5579b92000005555, fd = 21845, u32 = 21845, u64 = 6159157512495977813}}, {events = 21845, 
            data = {ptr = 0xa6, fd = 166, u32 = 166, u64 = 166}}, {events = 1434040609, data = {ptr = 0x9800005555, fd = 21845, u32 = 21845, u64 = 652835050837}}, {
            events = 0, data = {ptr = 0x55555578a964, fd = 1433971044, u32 = 1433971044, u64 = 93824994552164}}, {events = 1433972272, data = {ptr = 0x9800005555, 
              fd = 21845, u32 = 21845, u64 = 652835050837}}, {events = 0, data = {ptr = 0x55555579b9c6, fd = 1434040774, u32 = 1434040774, u64 = 93824994621894}}, {
            events = 116, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x55555579b920, fd = 1434040608, u32 = 1434040608, 
              u64 = 93824994621728}}, {events = 166, data = {ptr = 0x5579b92100000000, fd = 0, u32 = 0, u64 = 6159157516790923264}}, {events = 21845, data = {
              ptr = 0x2c, fd = 44, u32 = 44, u64 = 44}}, {events = 1433970689, data = {ptr = 0x5578724000005555, fd = 21845, u32 = 21845, u64 = 6158798109632648533}}, {
            events = 21845, data = {ptr = 0x55555578a8f0, fd = 1433970928, u32 = 1433970928, u64 = 93824994552048}}, {events = 1433970928, data = {
              ptr = 0x5578aa5000005555, fd = 21845, u32 = 21845, u64 = 6158859751003280725}}, {events = 21845, data = {ptr = 0x555555787240 <ctx>, fd = 1433956928, 
              u32 = 1433956928, u64 = 93824994538048}}}
        i = 0
---Type <return> to continue, or q <return> to quit---
#13 0x000055555555c669 in run () at /builddir/fastd-17/src/fastd.c:617
No locals.
#14 main (argc=<optimized out>, argv=<optimized out>) at /builddir/fastd-17/src/fastd.c:679
No locals.
(gdb) 
```

**Comment by ebfe** [comment]
> Program received signal SIGILL, Illegal instruction.
> 0x000055555557ac32 in _mm_shuffle_epi8

Does the cpu support SSSE3?

**Comment by Gottox** [comment]
Fixed by disabling ssse3.
