### ISSUE TITLE
Mypaint not starting

### ISSUE THREAD

**Issue by ncmprhnsbl** [voidlinux/void-packages#3215]
after recent mypaint update(>1.2.0_1) , failing to start with output:
```
$ mypaint
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/usr'
Traceback (most recent call last):
  File "/usr/bin/mypaint", line 442, in <module>
    = get_paths()
  File "/usr/bin/mypaint", line 220, in get_paths
    from lib import fileutils
  File "/usr/share/mypaint/lib/fileutils.py", line 31, in <module>
    import lib.gichecks  # this module can be imported early
  File "/usr/share/mypaint/lib/gichecks.py", line 16, in <module>
    import gi
ImportError: No module named gi
```
then i tried downgrading:
```
$ mypaint
0
Using GTK2

** (process:7871): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (process:7871): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (process:7871): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
builtin python 2.6 json support
DEBUG: getlocale(): ('en_AU', 'UTF-8')
DEBUG: localepath:  /usr/share/locale
DEBUG: localepath_brushlib:  /usr/share/locale
Traceback (most recent call last):
  File "/usr/bin/mypaint", line 198, in <module>
    from gui import main
  File "/usr/share/mypaint/gui/main.py", line 19, in <module>
    from gui import application
  File "/usr/share/mypaint/gui/application.py", line 16, in <module>
    import filehandling, keyboard, brushmanager, windowing, document, layout
  File "/usr/share/mypaint/gui/filehandling.py", line 17, in <module>
    from lib import document, helpers, tiledsurface
  File "/usr/share/mypaint/lib/document.py", line 16, in <module>
    import xml.etree.ElementTree as ET
ImportError: No module named etree.ElementTree
```

**Comment by ncmprhnsbl** [comment]
could have swore i checked that (python-gobject)  :o: 
thanks for the quick response :)
