### ISSUE TITLE
fail2ban run script is incorrect

### ISSUE THREAD

**Issue by jsumners** [voidlinux/void-packages#3545]
fail2ban does things in a silly way. The shipped `fail2ban-server` script isn't meant to actually start the server. In fact, it hard codes some configuration values (socket and pidfile). The right way to start fail2ban is with the `fail2ban-client` script. Thus, the run script should be:

```
#!/bin/sh
fail2ban-client start
exec pause
```

**Comment by xtraeme** [comment]
Care to submit a proper pull request?

**Comment by jsumners** [comment]
Turns out even that script isn't sufficient. I've submitted a query to upstream.

**Comment by cr6git** [comment]
> I've submitted a query to upstream.

What was their response?

**Comment by jsumners** [comment]
I don't know if they ever resolved the issue. This got lost in my stack and I forgot about it.

**Comment by cr6git** [comment]
Do you still use `fail2ban` ? 
Today our goal is to determine whether the problem you decribed is resolved.

**Comment by jsumners** [comment]
Actually, I just disabled it a couple days ago since this never got resolved (to my knowledge).

The issue looks to be https://github.com/fail2ban/fail2ban/issues/1139 and the fix merged in https://github.com/fail2ban/fail2ban/pull/1413 . Given that Void is shipping version "0.10.1" this might actually be resolved.

Indeed, it looks like the startup script is very close to what they suggest in https://github.com/fail2ban/fail2ban/blob/309a1cb337604e03f764bf50839bdd3cb8280757/files/fail2ban.service.in . Void is doing `fail2ban-server -f` and may benefit from `fail2ban-server -xf`. A stop script might also be a good thing to supply since it looks like they use `fail2ban-client stop` to shut down the server.

**Comment by cr6git** [comment]
Did you try the command mentioned by sebres? 
````
$ fail2ban-testcases -fn
Fail2ban 0.10.1 test suite. Python 2.7.14 (default, Sep 18 2017, 08:48:18) [GCC 6.3.0]. Please wait...
......................s.s.............................................F......................................................................s...s.......ss.......................................s..............sss.............s......sssssssssssssss..............................................................................................EE........
.....................EE........ssssss..................s..
======================================================================
ERROR: testSampleRegexsZZZ-GENERIC-EXAMPLE (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fail2ban/tests/samplestestcase.py", line 189, in testFilter
    flt = self._readFilter(fltName, name, basedir, opts=None)
  File "/usr/lib/python2.7/site-packages/fail2ban/tests/samplestestcase.py", line 102, in _readFilter
    filterConf.getOptions({})
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configreader.py", line 319, in getOptions
    self, "Definition", self._configOpts, pOpts)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configreader.py", line 147, in getOptions
    return self._cfg.getOptions(section, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configreader.py", line 245, in getOptions
    v = self.get(sec, optname, vars=pOptions)
  File "/usr/lib/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configparserinc.py", line 73, in _interpolate_some
    return self._cp_interpolate_some(option, accum, rest, section, map, *args, **kwargs)
  File "/usr/lib/python2.7/ConfigParser.py", line 723, in _interpolate_some
    option, section, rest, var)
InterpolationMissingOptionError: Bad value substitution:
	section: [Definition]
	option : ignoreregex
	key    : __prefix_line
	rawval : F2B: error from 192.0.2.251$
^%(__prefix_line)sF2B: error from 192.0.2.252$


======================================================================
ERROR: testSampleRegexsZZZ-SSHD-OBSOLETE-MULTILINE (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fail2ban/tests/samplestestcase.py", line 169, in testFilter
    flt = self._readFilter(fltName, name, basedir, opts=opts)
  File "/usr/lib/python2.7/site-packages/fail2ban/tests/samplestestcase.py", line 102, in _readFilter
    filterConf.getOptions({})
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configreader.py", line 319, in getOptions
    self, "Definition", self._configOpts, pOpts)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configreader.py", line 147, in getOptions
    return self._cfg.getOptions(section, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configreader.py", line 245, in getOptions
    v = self.get(sec, optname, vars=pOptions)
  File "/usr/lib/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configparserinc.py", line 73, in _interpolate_some
    return self._cp_interpolate_some(option, accum, rest, section, map, *args, **kwargs)
  File "/usr/lib/python2.7/ConfigParser.py", line 726, in _interpolate_some
    section, map, depth + 1)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configparserinc.py", line 73, in _interpolate_some
    return self._cp_interpolate_some(option, accum, rest, section, map, *args, **kwargs)
  File "/usr/lib/python2.7/ConfigParser.py", line 726, in _interpolate_some
    section, map, depth + 1)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configparserinc.py", line 73, in _interpolate_some
    return self._cp_interpolate_some(option, accum, rest, section, map, *args, **kwargs)
  File "/usr/lib/python2.7/ConfigParser.py", line 723, in _interpolate_some
    option, section, rest, var)
InterpolationMissingOptionError: Bad value substitution:
	section: [Definition]
	option : failregex
	key    : __prefix_line
	rawval : %(__pref)s


======================================================================
ERROR: testFullGeneric (fail2ban.tests.fail2banregextestcase.Fail2banRegexTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fail2ban/tests/fail2banregextestcase.py", line 254, in testFullGeneric
    self.assertTrue(fail2banRegex.start(args))
  File "/usr/lib/python2.7/site-packages/fail2ban/client/fail2banregex.py", line 586, in start
    if not self.readRegex(cmd_regex, 'fail'): # pragma: no cover
  File "/usr/lib/python2.7/site-packages/fail2ban/client/fail2banregex.py", line 339, in readRegex
    reader.getOptions(None)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configreader.py", line 319, in getOptions
    self, "Definition", self._configOpts, pOpts)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configreader.py", line 147, in getOptions
    return self._cfg.getOptions(section, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configreader.py", line 245, in getOptions
    v = self.get(sec, optname, vars=pOptions)
  File "/usr/lib/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configparserinc.py", line 73, in _interpolate_some
    return self._cp_interpolate_some(option, accum, rest, section, map, *args, **kwargs)
  File "/usr/lib/python2.7/ConfigParser.py", line 723, in _interpolate_some
    option, section, rest, var)
InterpolationMissingOptionError: Bad value substitution:
	section: [Definition]
	option : ignoreregex
	key    : __prefix_line
	rawval : F2B: error from 192.0.2.251$
^%(__prefix_line)sF2B: error from 192.0.2.252$


======================================================================
ERROR: testMultilineSshd (fail2ban.tests.fail2banregextestcase.Fail2banRegexTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fail2ban/tests/fail2banregextestcase.py", line 243, in testMultilineSshd
    self.assertTrue(fail2banRegex.start(args))
  File "/usr/lib/python2.7/site-packages/fail2ban/client/fail2banregex.py", line 586, in start
    if not self.readRegex(cmd_regex, 'fail'): # pragma: no cover
  File "/usr/lib/python2.7/site-packages/fail2ban/client/fail2banregex.py", line 339, in readRegex
    reader.getOptions(None)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configreader.py", line 319, in getOptions
    self, "Definition", self._configOpts, pOpts)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configreader.py", line 147, in getOptions
    return self._cfg.getOptions(section, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configreader.py", line 245, in getOptions
    v = self.get(sec, optname, vars=pOptions)
  File "/usr/lib/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configparserinc.py", line 73, in _interpolate_some
    return self._cp_interpolate_some(option, accum, rest, section, map, *args, **kwargs)
  File "/usr/lib/python2.7/ConfigParser.py", line 726, in _interpolate_some
    section, map, depth + 1)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configparserinc.py", line 73, in _interpolate_some
    return self._cp_interpolate_some(option, accum, rest, section, map, *args, **kwargs)
  File "/usr/lib/python2.7/ConfigParser.py", line 726, in _interpolate_some
    section, map, depth + 1)
  File "/usr/lib/python2.7/site-packages/fail2ban/client/configparserinc.py", line 73, in _interpolate_some
    return self._cp_interpolate_some(option, accum, rest, section, map, *args, **kwargs)
  File "/usr/lib/python2.7/ConfigParser.py", line 723, in _interpolate_some
    option, section, rest, var)
InterpolationMissingOptionError: Bad value substitution:
	section: [Definition]
	option : failregex
	key    : __prefix_line
	rawval : %(__pref)s


======================================================================
FAIL: testActionsOutput (fail2ban.tests.actionstestcase.ExecuteActions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fail2ban/tests/actionstestcase.py", line 85, in testActionsOutput
    self.assertTrue( Utils.wait_for(lambda: (f.read() == "ip start 64\n"), 3) )
AssertionError: False is not true

----------------------------------------------------------------------
Ran 409 tests in 10.100s

FAILED (failures=1, errors=4, skipped=33)
````

**Comment by jsumners** [comment]
At this point I am of the opinion that the upstream project is a mess and may not be worth it at all.

**Comment by cr6git** [comment]
> A stop script might also be a good thing to supply since it looks like they use `fail2ban-client stop` to shut down the server.

You meant something like that? 
````
# /etc/sv/fail2ban/finish
#!/bin/sh
exec fail2ban-client stop
````

**Comment by cr6git** [comment]
In [Fail2ban#Create_Missing_Bits](https://wiki.voidlinux.eu/Fail2ban#Create_Missing_Bits) the Void wiki says: 

> the `fail2ban` package leaves out a couple of important bits: the `/var/{lib,run}/fail2ban` directories.

They are removed during the package build process: 
````
=> fail2ban-0.10.1_1: running post-install hook: 03-remove-empty-dirs ...
=> WARNING: fail2ban-0.10.1_1: removed empty dir: /var/lib/fail2ban
=> WARNING: fail2ban-0.10.1_1: removed empty dir: /run/fail2ban
=> WARNING: fail2ban-0.10.1_1: removed empty dir: /etc/fail2ban/jail.d
=> WARNING: fail2ban-0.10.1_1: removed empty dir: /etc/fail2ban/fail2ban.d
````

**Comment by jsumners** [comment]
Yes, that finish script looks correct.

I wrote that article on the wiki. It is likely very wrong since it was written while trying to get the pre-0.10.0 version to work correctly.

**Comment by cr6git** [comment]
> may benefit from `fail2ban-server -xf`

So, could it be a good thing to a make a pull request, to use this command in the `run` script and to add a `finish` script?

**Comment by cr6git** [comment]
Just to say, I stopped working on this.
