### ISSUE TITLE
Instant Segmentation Fault in redis-cli on Void Musl x86_64

### ISSUE THREAD

**Issue by bitshark** [voidlinux/void-packages#4100]
Problem appears to occur due to some sort of bug or misconfiguration in the system-wide jemalloc libraries, which the void redis package is linked against.

```bash
[user@dolphin redis-3.0.7]$ redis-cli
Could not connect to Redis at 127.0.0.1:6379: Connection refused
not connected> quitSegmentation fault
```

```bash
[user@dolphin redis-3.0.7]$ gdb redis-cli
GNU gdb (GDB) 7.11
Reading symbols from redis-cli...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/redis-cli 
Could not connect to Redis at 127.0.0.1:6379: Connection refused
not connected> q
                Program received signal SIGSEGV, Segmentation fault.
                                                                    0x00007ffff7b20856 in free () from /lib/libjemalloc.so.2
(gdb) 
#0  0x00007ffff7b20856 in free () from /lib/libjemalloc.so.2
#1  0x000055555556a7c2 in linenoise ()
#2  0x000055555555d359 in main ()
```

and this
```
[user@dolphin redis-3.0.7]$ strace redis-cli 
[user@dolphin redis-3.0.7]$ strace redis-cli 
execve("/usr/bin/redis-cli", ["redis-cli"], [/* 27 vars */]) = 0
arch_prctl(ARCH_SET_FS, 0x7f56457b2988) = 0
set_tid_address(0x7f56457b29c0)         = 3693
open("/etc/ld-musl-x86_64.path", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libjemalloc.so.2", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=260208, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\3403\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 2363392, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0x7f56452ce000
mmap(0x7f564550a000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x3c000) = 0x7f564550a000
mmap(0x7f564550e000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f564550e000
close(3)                                = 0
mprotect(0x7f564550a000, 12288, PROT_READ) = 0
mprotect(0x7f56457af000, 4096, PROT_READ) = 0
mprotect(0x55e814227000, 4096, PROT_READ) = 0
readlink("/etc/malloc.conf", 0x7ffe97217430, 4096) = -1 ENOENT (No such file or directory)
brk(NULL)                               = 0x55e814a71000
mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f56455af000
munmap(0x7f56455af000, 2097152)         = 0
mmap(NULL, 4190208, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5644ecf000
munmap(0x7f5644ecf000, 1249280)         = 0
munmap(0x7f5645200000, 843776)          = 0
sched_getaffinity(0, 128, [f, 0, 0, 0, 0, 0, 0, 0]) = 8
mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f56455af000
munmap(0x7f56455af000, 2097152)         = 0
mmap(NULL, 4190208, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5644c01000
munmap(0x7f5644c01000, 2093056)         = 0
ioctl(1, TIOCGWINSZ, {ws_row=44, ws_col=169, ws_xpixel=0, ws_ypixel=0}) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [], SA_RESTORER|SA_RESTART, 0x7f5645580bef}, {SIG_DFL, [], 0}, 8) = 0
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
connect(3, {sa_family=AF_INET, sin_port=htons(6379), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation in progress)
poll([{fd=3, events=POLLOUT}], 1, -1)   = 1 ([{fd=3, revents=POLLOUT|POLLERR|POLLHUP}])
getsockopt(3, SOL_SOCKET, SO_ERROR, [111], [4]) = 0
writev(2, [{"", 0}, {"Could not connect to Redis at ", 30}], 2Could not connect to Redis at ) = 30
writev(2, [{"127.0.0.1:6379: Connection refus"..., 35}, {NULL, 0}], 2127.0.0.1:6379: Connection refused
) = 35
close(3)                                = 0
ioctl(0, TIOCGWINSZ, {ws_row=44, ws_col=169, ws_xpixel=0, ws_ypixel=0}) = 0
open("/home/user/.rediscli_history", O_RDONLY) = -1 ENOENT (No such file or directory)
ioctl(0, TIOCGWINSZ, {ws_row=44, ws_col=169, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(0, TIOCGWINSZ, {ws_row=44, ws_col=169, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_CONTINUE or TCSETSF, {B38400 -opost -isig -icanon -echo ...}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=44, ws_col=169, ws_xpixel=0, ws_ypixel=0}) = 0
write(1, "not connected> ", 15not connected> )         = 15
read(0, "q", 1)                         = 1
not connected> q
) = 27
read(0, "\r", 1)                        = 1
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x55e814200158} ---
++++ killed by SIGSEGV +++
Segmentation fault
```

**Comment by bitshark** [comment]
FYI This should be resolved (at least as far as Redis goes) as of that commit and pull request referenced above. . . There's probably still an outstanding issue in the jemalloc shared libs on Void Linux Musl x86_64
