### ISSUE TITLE
Broken package: vagrant

### ISSUE THREAD

**Issue by DirectorX** [voidlinux/void-packages#4669]
i tried to create a new machine

```
➜  blog vagrant init
Bundler, the underlying system used to manage Vagrant plugins,
is reporting that a plugin or its dependency can't be found.
This is usually caused by manual tampering with the 'plugins.json'
file in the Vagrant home directory. To fix this error, please
remove that file and reinstall all your plugins using `vagrant
plugin install`.
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- log4r (LoadError)
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from /usr/lib/vagrant/gems/vagrant-1.8.5/bin/vagrant:104:in `<top (required)>'
    from /usr/lib/vagrant/bin/vagrant:23:in `load'
    from /usr/lib/vagrant/bin/vagrant:23:in `<main>'
```

it looks like something went wrong with ruby.

**Comment by Hoshpak** [comment]
It seems that your vagrant installation is missing the log4r gem. I tried to install the current vagrant package from the repository to reproduce the error. However the gem is currently installed in /usr/lib/vagrant/gems/log4r-1.1.10 and vagrant works fine for me. I guess the issue was fixed in the meantime, possibly during the last update of the vagrant package.
