### ISSUE TITLE
libtorrent-rasterbar-python-1.1.1_1 broken

### ISSUE THREAD

**Issue by cavalier911** [voidlinux/void-packages#4771]
x86_64 glibc
Errors on startup in classic mode:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/deluge/ui/gtkui/gtkui.py", line 349, in _on_reactor_start
    client.start_classic_mode()
  File "/usr/lib/python2.7/site-packages/deluge/ui/client.py", line 559, in start_classic_mode
    self._daemon_proxy = DaemonClassicProxy(self.__event_handlers)
  File "/usr/lib/python2.7/site-packages/deluge/ui/client.py", line 432, in __init__
    self.__daemon = deluge.core.daemon.Daemon(classic=True)
  File "/usr/lib/python2.7/site-packages/deluge/core/daemon.py", line 141, in __init__
    from deluge.core.core import Core
  File "/usr/lib/python2.7/site-packages/deluge/core/core.py", line 36, in <module>
    from deluge._libtorrent import lt
  File "/usr/lib/python2.7/site-packages/deluge/_libtorrent.py", line 59, in <module>
    import libtorrent as lt
ImportError: /usr/lib/python2.7/site-packages/libtorrent.so: undefined symbol: _ZN10libtorrent14session_handle14wait_for_alertEN5boost6chrono8durationIlNS1_5ratioILl1ELl1000000000EEEEE
```
Unable to start the daemon manually from the Connection Manager
Downgrading to libtorrent-rasterbar{-python}-1.0.9_2 reverts all problems.

**Comment by ebfe** [comment]
For some reason python bindings don't pick up `CXXFLAGS=-stc=c++11`.
