### ISSUE TITLE
Bug: Deluge musl x86_64

### ISSUE THREAD

**Issue by 38github** [voidlinux/void-packages#4834]
The system is up to date and when I start the newly installed deluge i get the following:

```
$ deluge

** (deluge:3114): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (deluge:3114): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (deluge:3114): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
[ERROR   ] 00:55:43 ui:171 Error relocating /lib/libglade-2.0.so.0: g_module_close: symbol not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/deluge/ui/ui.py", line 152, in __init__
    from deluge.ui.gtkui.gtkui import GtkUI
  File "/usr/lib/python2.7/site-packages/deluge/ui/gtkui/__init__.py", line 1, in <module>
    from gtkui import start
  File "/usr/lib/python2.7/site-packages/deluge/ui/gtkui/gtkui.py", line 58, in <module>
    import gtk, gtk.glade
ImportError: Error relocating /lib/libglade-2.0.so.0: g_module_close: symbol not found
[ERROR   ] 00:55:43 ui:172 There was an error whilst launching the request UI: gtk
[ERROR   ] 00:55:43 ui:173 Look at the traceback above for more information.

```

**Comment by 38github** [comment]
Bump.

**Comment by 38github** [comment]
Anyone has any idea? I would like to use Deluge instead of Transmission because it allows to use manual proxy/socks.
