### ISSUE TITLE
Mypaint fails to start

### ISSUE THREAD

**Issue by ncmprhnsbl** [voidlinux/void-packages#5104]
```
Traceback (most recent call last):
  File "/usr/bin/mypaint", line 462, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "/usr/share/mypaint/gui/main.py", line 92, in main
    lib.glib.init_user_dir_caches()
  File "/usr/share/mypaint/lib/glib.py", line 109, in init_user_dir_caches
    logger.debug("Init g_get_user_config_dir(): %r", get_user_config_dir())
  File "/usr/share/mypaint/lib/glib.py", line 71, in get_user_config_dir
    return filename_to_unicode(d_fs)
  File "/usr/share/mypaint/lib/glib.py", line 57, in filename_to_unicode
    ustring = GLib.filename_to_utf8(opsysstring, -1, 0, 0)
TypeError: GLib.filename_to_utf8() takes exactly 2 arguments (4 given)
```

**Comment by asergi** [comment]
Fixed.

**Comment by ncmprhnsbl** [comment]
thanks :+1:
