### ISSUE TITLE
snappy-player: x86_64 glibc segfaults

### ISSUE THREAD

**Issue by cavalier911** [voidlinux/void-packages#5187]
snappy-player-dbg-1.0_2.x86_64.xbps
````
(gdb) bt full
#0  __GI___pthread_mutex_lock (mutex=0x73646e756f)
    at ../nptl/pthread_mutex_lock.c:67
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        type = <optimized out>
        id = <optimized out>
#1  0x00007ffff6b78cda in XrmQGetResource () from /usr/lib/libX11.so.6
No symbol table info available.
#2  0x00007ffff6b55146 in XGetDefault () from /usr/lib/libX11.so.6
No symbol table info available.
#3  0x00007fffef47d868 in _XcursorGetDisplayInfo ()
   from /usr/lib/libXcursor.so.1
No symbol table info available.
#4  0x00007fffef47da19 in XcursorGetTheme () from /usr/lib/libXcursor.so.1
No symbol table info available.
#5  0x00007ffff5f8523f in gdk_x11_display_set_cursor_theme ()
   from /usr/lib/libgdk-3.so.0
No symbol table info available.
#6  0x00007ffff64e5201 in ?? () from /usr/lib/libgtk-3.so.0
No symbol table info available.
#7  0x00007ffff64ea3df in ?? () from /usr/lib/libgtk-3.so.0
No symbol table info available.
#8  0x00007ffff63b56c6 in ?? () from /usr/lib/libgtk-3.so.0
No symbol table info available.
---Type <return> to continue, or q <return> to quit---q
Quit
````
[Bug 750167 - snappy segfaults at start ](https://bugzilla.gnome.org/show_bug.cgi?id=750167)

**Comment by ebfe** [comment]
Multiple updates since the issue was filed. Feel free to reopen if the problem persists.
