### ISSUE TITLE
qt5-5.7.1: strange build error

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5396]
I'm preparing the update of qt5 to 5.7.1 and see a strange error **when _not_ cross compiling**!
For cross targets the build succeeds and here's the error I see when trying to build for e.g. x86_64 or x86_64-musl:

```
using python: /usr/bin/python version: 2.7.13
Using extra options found in /builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/core/qmake_extras.gypi
Using extra options found in /builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/core/qtwebengine_extras.gypi
Using extra options found in /builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/core/qmake_extras.gypi
Using extra options found in /builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/core/qtwebengine_extras.gypi
Updating projects from gyp files...
/bin/sh: @echo: command not found
compiler_version.py failed to execute: @echo compiling gyp_run.pro && g++ -Xassembler --version -x assembler -c /dev/null
Command '@echo compiling gyp_run.pro && g++ -Xassembler --version -x assembler -c /dev/null' returned non-zero exit status 127
Exception: Failed to extract compiler version for args: ['target', 'assembler']
Traceback (most recent call last):
  File "/builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/3rdparty/chromium/tools/gyp/pylib/gyp/input.py", line 496, in CallLoadTargetBuildFile
    includes, depth, check, False)
  File "/builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/3rdparty/chromium/tools/gyp/pylib/gyp/input.py", line 417, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "/builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/3rdparty/chromium/tools/gyp/pylib/gyp/input.py", line 1214, in ProcessVariablesAndConditionsInDict
    variables, build_file, 'variables')
  File "/builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/3rdparty/chromium/tools/gyp/pylib/gyp/input.py", line 1266, in ProcessVariablesAndConditionsInDict
    ProcessConditionsInDict(the_dict, phase, variables, build_file)
  File "/builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/3rdparty/chromium/tools/gyp/pylib/gyp/input.py", line 1145, in ProcessConditionsInDict
    variables, build_file)
  File "/builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/3rdparty/chromium/tools/gyp/pylib/gyp/input.py", line 1266, in ProcessVariablesAndConditionsInDict
    ProcessConditionsInDict(the_dict, phase, variables, build_file)
  File "/builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/3rdparty/chromium/tools/gyp/pylib/gyp/input.py", line 1145, in ProcessConditionsInDict
    variables, build_file)
  File "/builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/3rdparty/chromium/tools/gyp/pylib/gyp/input.py", line 1221, in ProcessVariablesAndConditionsInDict
    expanded = ExpandVariables(value, phase, variables, build_file)
  File "/builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/3rdparty/chromium/tools/gyp/pylib/gyp/input.py", line 891, in ExpandVariables
    replacement = str(py_module.DoMain(parsed_contents[1:])).rstrip()
  File "/builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/3rdparty/chromium/build/compiler_version.py", line 107, in DoMain
    raise Exception("Failed to extract compiler version for args: %s" % args)
Exception: Failed to extract compiler version for args: ['target', 'assembler']
…
```

I'm searching for solutions to this problem and help is welcome.

Other than that the new version dropped support for qt5-enginio (was deprecated and is now removed), dropped the qt5-plugin-gtk2 (there's now a styleplugin but people on forums are reporting issues with apps expecting the gtk theme). Finally 5.7.1 adds a few new shared libraries. No shlib revbumping orgy is required - the existing shlib versions remain unchanged.

**Comment by pullmoll** [comment]
Note: I could try to patch `compiler_version.py` to return a fixed version number for the GNU assembler instead of executing the command to determine it but that would of course be a gross hack.

**Comment by pullmoll** [comment]
Another note: https://bugreports.qt.io/browse/QTBUG-41112
It seems our template should unset CC CXX and LD for native builds - trying that now.

**Comment by pullmoll** [comment]
Unsetting the environment CC, CXX and LD indeed works. Now I'm going to compile for all arches, test the x86_64 build here and, if my Qt5 apps (qbittorrent, qupzilla, qtcreator, own projects) still work, push the update later on.

**Comment by pullmoll** [comment]
It seems I have solved this issue by setting _some_ of the environment variables.
Building for all architectures now and testing locally.

Some new components / submodules will be in 5.7.1: `qt5-charts`, `qt5-datavis3d`, `qt5-gamepad` and `qt5-virtualkeyboard` with their respective development subpkgs.
