### ISSUE TITLE
python 2.7.13: qt5 build hangs in webkit for i686

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5432]
Building qt5 for i686 used to work <s>with the previous python2</s>.
Now it hangs at
```
python /builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/tools/buildscripts/gyp_qtwebengine …
```
being run `$XBPS_MAKE_JOBS` times in parallel, while seemingly one or all process(es) wait for a lock or each other. This looks like an i686 specific lock or semaphore issue with python?

To reproduce the issue run `./xbps-src -m i686 binary-bootstrap i686` and `./xbps-src -m i686 pkg qt5` and wait until after `libtQt5ScriptTools.so.5.7.1` is built.

Edit: Oops! No, qt5 was updated after python and thus built with python-2.7.13 before, so the reason has to be something else.

**Comment by pullmoll** [comment]
When running with `XBPS_MAKE_JOBS=1` it takes long to get to the point and then this error is printed:
```
Project MESSAGE: Running gyp_qtwebengine "/builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/core" -D qt_cross_compile=0 -D qt_os="desktop_linux" -D pkg-config="pkg-config 2> /dev/null" -D use_qt=1 -D v8_use_external_startup_data=0 -D enable_basic_printing=1 -D enable_print_preview=0 -D enable_web_speech=0 -D enable_extensions=0 -D linux_use_bundled_gold=0 -D linux_use_bundled_binutils=0 -D linux_use_gold_flags=0 -D toolkit_uses_gtk=0 -D use_ash=0 -D use_aura=1 -D use_cairo=0 -D use_clipboard_aurax11=0 -D use_cups=0 -D use_gconf=0 -D use_gio=0 -D use_gnome_keyring=0 -D use_kerberos=0 -D use_pango=0 -D use_openssl=1 -D use_nss_certs=1 -D use_openssl_certs=0 -D no_delete_null_pointer_checks=1 -D use_system_zlib=1 -D use_system_libpng=1 -D use_system_libjpeg=1 -D use_system_harfbuzz=1 -D use_pulseaudio=1 -D use_alsa=1 -D use_system_libwebp=1 -D use_system_libsrtp=1 -D use_system_libxml=1 -D use_system_snappy=1 -D desktop_linux=1 -D enable_widevine=1 -D clang=0 -D host_clang=0 -D qtwe_process_name_debug=QtWebEngineProcess -D qtwe_process_name_release=QtWebEngineProcess -D disable_glibcxx_debug=1 -D remove_webcore_debug_symbols=1 -D remove_v8base_debug_symbols=1 -D disable_fatal_linker_warnings=1 -D sysroot="" -D target_arch=ia32 -D enable_spellcheck=0.
using python: /usr/bin/python version: 2.7.13
Using extra options found in /builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/core/qmake_extras.gypi
Using extra options found in /builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/core/qtwebengine_extras.gypi
Using extra options found in /builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/core/qmake_extras.gypi
Using extra options found in /builddir/qt-everywhere-opensource-src-5.7.1/qtwebengine/src/core/qtwebengine_extras.gypi
Updating projects from gyp files...
Process PoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 380, in get
    rrelease()
ValueError: semaphore or lock released too many times
```

**Comment by pullmoll** [comment]
Comparing with #5425, which also happens for i686 only, this is starting to look like a gcc-6.3.0 issue.

**Comment by pullmoll** [comment]
The same problem occurs when trying to build `firefox-esr` for `i686`.

**Comment by pullmoll** [comment]
I was hinted to this solution (?) by https://cygwin.com/ml/cygwin/2013-11/msg00001.html
The patch there was wrong, because it assigned the return value of `sem_getvalue()` to sval.
The patch I devised saves the return value of `sem_getvalue()` and only compares `sval` to `self->maxvalue`, if the result was zero, i.e. if sval was set.

I'm not 100% sure this is correct, while it fixes the problem(s) with i686 builds here.
