### ISSUE TITLE
calibre segfaults on startup

### ISSUE THREAD

**Issue by edwintorok** [voidlinux/void-packages#5635]
With calibre 2.77 from the void repository:

```
$ gdb --args /usr/bin/python2 /usr/bin/calibre
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python2...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/python2 /usr/bin/calibre
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) bt

#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff7a6d4f9 in PyString_FromFormatV () from /usr/lib/libpython2.7.so.1.0
#2  0x00007ffff7ada2fc in PyErr_Format () from /usr/lib/libpython2.7.so.1.0
#3  0x00007fffe8f038ea in ?? () from /usr/lib/python2.7/site-packages/sip.so
#4  0x00007fffe01682e6 in initprogress_indicator () from /usr/lib/calibre/calibre/plugins/progress_indicator.so
#5  0x00007ffff7ae658c in _PyImport_LoadDynamicModule () from /usr/lib/libpython2.7.so.1.0
#6  0x00007ffff7ae3de1 in ?? () from /usr/lib/libpython2.7.so.1.0
#7  0x00007ffff7ae4cce in PyImport_ImportModuleLevel () from /usr/lib/libpython2.7.so.1.0
#8  0x00007ffff7ac29b8 in ?? () from /usr/lib/libpython2.7.so.1.0
#9  0x00007ffff7acc7b4 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#10 0x00007ffff7ace90c in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#11 0x00007ffff7acc2e1 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#12 0x00007ffff7acc403 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#13 0x00007ffff7ace90c in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#14 0x00007ffff7a4276c in ?? () from /usr/lib/libpython2.7.so.1.0
#15 0x00007ffff7a10353 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#16 0x00007ffff7a2202c in ?? () from /usr/lib/libpython2.7.so.1.0
#17 0x00007ffff7a10353 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#18 0x00007ffff7a84d17 in ?? () from /usr/lib/libpython2.7.so.1.0
#19 0x00007ffff7ac7515 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#20 0x00007ffff7ace90c in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#21 0x00007ffff7a42855 in ?? () from /usr/lib/libpython2.7.so.1.0
#22 0x00007ffff7a10353 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#23 0x00007ffff7a2202c in ?? () from /usr/lib/libpython2.7.so.1.0
#24 0x00007ffff7a10353 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#25 0x00007ffff7a82372 in ?? () from /usr/lib/libpython2.7.so.1.0
#26 0x00007ffff7a7e87e in ?? () from /usr/lib/libpython2.7.so.1.0
#27 0x00007ffff7a10353 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#28 0x00007ffff7ac9fad in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#29 0x00007ffff7acc403 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#30 0x00007ffff7ace90c in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#31 0x00007ffff7acc2e1 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#32 0x00007ffff7ace90c in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
```

```
valgrind shows
==21362== Process terminating with default action of signal 11 (SIGSEGV)
==21362==  Access not within mapped region at address 0xC0
==21362==    at 0x4A0AFB2: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==21362==    by 0x4CDF4F8: PyString_FromFormatV (in /usr/lib/libpython2.7.so.1.0)
==21362==    by 0x4D4C2FB: PyErr_Format (in /usr/lib/libpython2.7.so.1.0)
==21362==    by 0x151D98E9: ??? (in /usr/lib/python2.7/site-packages/sip.so)
==21362==    by 0x1E7992E5: initprogress_indicator (in /usr/lib/calibre/calibre/plugins/progress_indicator.so)
==21362==    by 0x4D5858B: _PyImport_LoadDynamicModule (in /usr/lib/libpython2.7.so.1.0)
==21362==    by 0x4D55DE0: ??? (in /usr/lib/libpython2.7.so.1.0)
==21362==    by 0x4D56CCD: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==21362==    by 0x4D349B7: ??? (in /usr/lib/libpython2.7.so.1.0)
==21362==    by 0x4D3E7B3: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==21362==    by 0x4D4090B: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==21362==    by 0x4D3E2E0: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
...


If I rebuild 2.77 using void-packages from git then it doesn't crash on startup.

**Comment by ebfe** [comment]
Seems solved by #5636
