### ISSUE TITLE
Fails when start Variety 

### ISSUE THREAD

**Issue by diogoleal** [voidlinux/void-packages#5663]
A dependence doesn't resolve for Variety.

```
/usr/lib/python2.7/site-packages/variety/__init__.py:105: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GObject # pylint: disable=E0611
Traceback (most recent call last):
  File "/usr/bin/variety", line 38, in <module>
    import variety
  File "/usr/lib/python2.7/site-packages/variety/__init__.py", line 107, in <module>
    from variety import VarietyWindow
  File "/usr/lib/python2.7/site-packages/variety/VarietyWindow.py", line 22, in <module>
    from variety.FacebookHelper import FacebookHelper
  File "/usr/lib/python2.7/site-packages/variety/FacebookHelper.py", line 55, in <module>
    from variety.Util import Util
  File "/usr/lib/python2.7/site-packages/variety/Util.py", line 28, in <module>
    import pyexiv2
ImportError: No module named pyexiv2
```

**Comment by ebfe** [comment]
Looks like we never had pyexiv2 packaged. Did this ever work?

**Comment by CoolOhm** [comment]
This problem has existed for a while. I brought it up on the Void forum [back in November](https://forum.voidlinux.eu/t/variety-package-and-missing-pyexiv2/1415), and someone said they had contacted the maintainer. No idea what the status is though.
