### ISSUE TITLE
ansible stopped working, complains about missing packaging distribution

### ISSUE THREAD

**Issue by Hoshpak** [voidlinux/void-packages#6044]
ansible does no longer work, it complains that it cannot find the packaging distribution which is required by cryptography, full backtrace:

```
[helmut@sheldon ~]$ ansible -vvv -i /tmp/inventor -m setup 127.0.0.1
No config file found; using defaults
ERROR! Unexpected Exception: The 'packaging' distribution was not found and is required by cryptography
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible", line 103, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/adhoc.py", line 202, in run
    result = self._tqm.run(play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 209, in run
    self.load_callbacks()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 177, in load_callbacks
    for callback_plugin in callback_loader.all(class_only=True):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 394, in all
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 324, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/callback/foreman.py", line 30, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 11, in <module>
    from cryptography import utils
  File "/usr/lib/python2.7/site-packages/cryptography/utils.py", line 13, in <module>
    from pkg_resources.extern.packaging.version import parse
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'packaging' distribution was not found and is required by cryptography
```

**Comment by asergi** [comment]
af593136f35746d70a379f2a62147afaae85e7d6

**Comment by asergi** [comment]
As of 1.9, `cryptography` no longer depends on `packaging`.
