### ISSUE TITLE
xorg-server: crash at start if libEGL is not installed

### ISSUE THREAD

**Issue by masato9000** [voidlinux/void-packages#6091]
This probably only affects drivers that default to using glamor, or if a user deliberately selects it as the accelmethod in xorg.conf.d.

When using the "modesetting" driver, starting the xserver will cause it to terminate on startup, after loading the glamor module if libEGL is not installed.  The console is completely locked (the machine is actually still running but you can only reboot it at this point via ssh or power button/acpid).

Xorg's libglamoregl.so doesn't actually link against libEGL, so it doesn't get added to shlibd depends.

There are a couple of ways to handle this.
* add libEGL dependency to xorg-server template
* add an xorg.conf.d snippet for the modesetting driver where AccelMethod is set to None

Note that _glamor doesn't actually work_, for reasons I've yet to discover, but Xorg will start up successfully, and you'll just lack acceleration.  (I haven't figured out what else we need, but it seems to be related to the xorg log message <code>EGL_MESA_drm_image required</code>.)

Users of qemu VMs seem most likely to run into this issue.

**Comment by masato9000** [comment]
Note: the part about whether glamor actually works _isn't important to the issue_ (and I've in fact already given up on that for now; it might be too reliant on experimental features, and I'm not knowledgable enough about all the pieces involved to really spend a lot of time on it).

So the issue is just about deciding which way is better to deal with the crash when libEGL isn't found...

**Comment by kraj** [comment]
here is backtrace from OpenEmbedded build but relevant to this issue as well.

#0  __restore_sigs (set=set@entry=0x7fe43dc4f8) at /usr/src/debug/musl/1.1.16+gitAUTOINC+da438ee1fc-r0/git/src/signal/block.c:44
#1  0x0000007f90a7f1c4 in raise (sig=sig@entry=6) at /usr/src/debug/musl/1.1.16+gitAUTOINC+da438ee1fc-r0/git/src/signal/raise.c:13
#2  0x0000007f90a4b648 in abort () at /usr/src/debug/musl/1.1.16+gitAUTOINC+da438ee1fc-r0/git/src/exit/abort.c:9
#3  0x0000005571394420 in OsAbort () at /usr/src/debug/xserver-xorg/2_1.19.3-r0/xorg-server-1.19.3/os/utils.c:1355
#4  0x000000557128d5dc in ddxGiveUp (error=EXIT_ERR_ABORT) at /usr/src/debug/xserver-xorg/2_1.19.3-r0/xorg-server-1.19.3/hw/xfree86/common/xf86Init.c:1010
#5  0x000000557139a188 in AbortServer () at /usr/src/debug/xserver-xorg/2_1.19.3-r0/xorg-server-1.19.3/os/log.c:874
#6  0x000000557139afb0 in FatalError (f=f@entry=0x55713c7350 "Caught signal %d (%s). Server aborting\n") at /usr/src/debug/xserver-xorg/2_1.19.3-r0/xorg-server-1.19.3/os/log.c:1015
#7  0x00000055713917fc in OsSigHandler (signo=11, sip=0x7fe43dc750, unused=<optimized out>) at /usr/src/debug/xserver-xorg/2_1.19.3-r0/xorg-server-1.19.3/os/osinit.c:154
#8  <signal handler called>
#9  0x0000007f8f912ec8 in _eglInternalError (msg=0x7f8f922ae0 <__func__.9779> "eglQueryString", errCode=12288) at /usr/src/debug/mesa/2_17.1.7-r0/mesa-17.1.7/src/egl/main/eglcurrent.c:230
#10 _eglError (errCode=errCode@entry=12288, msg=msg@entry=0x7f8f922ae0 <__func__.9779> "eglQueryString") at /usr/src/debug/mesa/2_17.1.7-r0/mesa-17.1.7/src/egl/main/eglcurrent.c:297
#11 0x0000007f8f90c3d8 in eglQueryString (dpy=<optimized out>, name=<optimized out>) at /usr/src/debug/mesa/2_17.1.7-r0/mesa-17.1.7/src/egl/main/eglapi.c:662
#12 0x0000007f901ec95c in epoxy_has_egl_extension (dpy=dpy@entry=0x0, ext=ext@entry=0x7f902713e0 "EGL_EXT_platform_base") at /usr/src/debug/libepoxy/1.4.3-r0/libepoxy-1.4.3/src/dispatch_egl.c:96
#13 0x0000007f902561c0 in glamor_egl_get_display (type=12759, native=0x557b7eed80) at /usr/src/debug/xserver-xorg/2_1.19.3-r0/xorg-server-1.19.3/glamor/glamor_egl.h:64
#14 glamor_egl_init (scrn=scrn@entry=0x557b7d4800, fd=9) at /usr/src/debug/xserver-xorg/2_1.19.3-r0/xorg-server-1.19.3/glamor/glamor_egl.c:770
#15 0x0000007f90293d38 in try_enable_glamor (pScrn=0x557b7d4800) at /usr/src/debug/xserver-xorg/2_1.19.3-r0/xorg-server-1.19.3/hw/xfree86/drivers/modesetting/driver.c:754
#16 PreInit (pScrn=0x557b7d4800, flags=85) at /usr/src/debug/xserver-xorg/2_1.19.3-r0/xorg-server-1.19.3/hw/xfree86/drivers/modesetting/driver.c:986
#17 0x000000557128f254 in InitOutput (pScreenInfo=pScreenInfo@entry=0x5571406a30 <screenInfo>, argc=argc@entry=4, argv=argv@entry=0x7fe43ddce8)
    at /usr/src/debug/xserver-xorg/2_1.19.3-r0/xorg-server-1.19.3/hw/xfree86/common/xf86Init.c:582
#18 0x000000557124eef8 in dix_main (argc=4, argv=0x7fe43ddce8, envp=<optimized out>) at /usr/src/debug/xserver-xorg/2_1.19.3-r0/xorg-server-1.19.3/dix/main.c:197
#19 0x0000007f90a4aecc in __libc_start_main (main=0x5571237f40 <main>, argc=4, argv=0x7fe43ddce8) at /usr/src/debug/musl/1.1.16+gitAUTOINC+da438ee1fc-r0/git/src/env/__libc_start_main.c:74
#20 0x0000005571237f94 in _start_c (p=<optimized out>) at /usr/src/debug/musl/1.1.16+gitAUTOINC+da438ee1fc-r0/git/crt/crt1.c:17

**Comment by masato9000** [comment]
It looks like no decision on this has been made, and I may have recently realized part of the problem.

It's not a good idea to add a direct _package_ dependency on libEGL for any package as that could mean conflicts between mesa and nvidia-libs.  And disabling accel by default would suck too since I think the radeon/amdgpu drivers also use glamor.

Even an shlib depend (I don't recall if we can arbitrarily add them) would still need the system to pick one from the choices as the default, and it could mean headaches for users of the nondefault option (I'm not currently aware of how xbps deals with conflict resolution between packages that are deps)

**Comment by chrstfer** [comment]
I had this exact problem just now, except that my terminal didn't lock out. The server would crash after trying to load glamour, and xinit would time out and exit. I had just switched back to nouveau from the nvidia drivers, and this happened. Installing libEGL fixed it. 

Oddly enough, I am using void, but the search that lead to this result didn't mention void, or glamour.
