### ISSUE TITLE
Python 2.7.13 race condition with multiprocessing (i686)

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#7468]
The error I hoped to have fixed with setting `CFLAGS="-DHAVE_BROKEN_SEM_GETVALUE=1"` in python's template is back with gcc-7.2.0.

Here's an example output when trying to build qt5 for i686, python hanging in some loop when configuring the embedded qtwebengine (i.e. Chrome) and me finally hitting Ctrl+C:
```
^CProcess PoolWorker-10:
Traceback (most recent call last):
Process PoolWorker-6:
Process PoolWorker-13:
Process PoolWorker-7:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-9:
Process PoolWorker-15:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Process PoolWorker-8:
Process PoolWorker-14:
Process PoolWorker-11:
Traceback (most recent call last):
Process PoolWorker-12:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
Process PoolWorker-2:
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    racquire()
KeyboardInterrupt
    task = get()
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
    self.run()
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    self._target(*self._args, **self._kwargs)
    racquire()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
KeyboardInterrupt
    racquire()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
KeyboardInterrupt
    task = get()
    self._target(*self._args, **self._kwargs)
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    racquire()
    racquire()
KeyboardInterrupt
KeyboardInterrupt
    task = get()
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
    task = get()
    task = get()
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 378, in get
    racquire()
    racquire()
    racquire()
    return recv()
KeyboardInterrupt
    racquire()
    racquire()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
Process PoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 380, in get
    rrelease()
ValueError: semaphore or lock released too many times
```

Perhaps someone else can make a guess as to why and how this happens, or how to solve the problem.

Otherwise I hope that switching to Qt5 5.9.x some day will fix the problem.

**Comment by pullmoll** [comment]
Another run exhibits different messages, even before hitting Ctrl+C:
```
Updating projects from gyp files...
make[3]: Nothing to be done for 'first'.
make[3]: Leaving directory '/builddir/qt-everywhere-opensource-src-5.8.0/qt3d/tools/qgltf'
make[2]: Leaving directory '/builddir/qt-everywhere-opensource-src-5.8.0/qt3d/tools'
make[1]: Leaving directory '/builddir/qt-everywhere-opensource-src-5.8.0/qt3d'
Process PoolWorker-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 378, in get
    return recv()
UnpicklingError: invalid load key, ''.
Process PoolWorker-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 378, in get
    return recv()
UnpicklingError: invalid load key, ''.
```

**Comment by ebfe** [comment]
To me it looks like HAVE_BROKEN_SEM_GETVALUE=1 is bogus and has nothing to do with the above error. If you look into the history of the patch it was a fix for a bug in the cygwin implementation.

**Comment by pullmoll** [comment]
Yes, it was probably pure coincidence that this change to python seemed to fix qt5 builds for i686 with gcc-6.3.0. The real bug is lurking elsewhere.

**Comment by pullmoll** [comment]
FWIW I now had the same problem with our current `gcc-6.3.0` trying to build `firefox-esr` for `i686`.
In a completely unknowing attempt to do something about it I applied the following patch to python and, funny enough, I can now build firefox-esr again.

It *may* again be a bogus change, while I've seen many places in the same source `Lib/multiprocessing/queues.py` which also don't create local aliases for the self._rlock and self._wlock methods.

I don't know anything about the innards of Python while I could imagine that creating an alias for a method involves stack memory or copying around of pointers or similar.

Anyway, I will try if this same patch also solves the reproducible problem with i686 python / gyp for gcc-7.2.0 as well.

This is the patch:
```patch
--- Lib/multiprocessing/queues.py       2017-09-16 19:38:35.000000000 +0200
+++ Lib/multiprocessing/queues.py       2017-10-24 19:49:06.291351206 +0200
@@ -369,13 +369,12 @@

     def _make_methods(self):
         recv = self._reader.recv
-        racquire, rrelease = self._rlock.acquire, self._rlock.release
         def get():
-            racquire()
-            try:
-                return recv()
-            finally:
-                rrelease()
+            self._rlock.acquire()
+            try:
+                return recv()
+            finally:
+                self._rlock.release()
         self.get = get

         if self._wlock is None:
@@ -383,11 +382,10 @@
             self.put = self._writer.send
         else:
             send = self._writer.send
-            wacquire, wrelease = self._wlock.acquire, self._wlock.release
             def put(obj):
-                wacquire()
-                try:
-                    return send(obj)
-                finally:
-                    wrelease()
+                self._wlock.acquire()
+                try:
+                    return send(obj)
+                finally:
+                    self._wlock.release()
             self.put = put

```

**Comment by pullmoll** [comment]
Another observation: A cross built python for i686 still hangs in the mentioned packages. Re-building python in the "native" i686 environment then fixes the problem.

It seems as if cross building python from x86_64 for i686 results in subtle differences and breakage. Perhaps something along the lines of pointer size (8 vs. 4) or sizeof(off_t) etc. as mentioned in #9143

**Comment by pullmoll** [comment]
Closing. It's the cross build for i686 that causes python2.7 to fail and can be solved by building natively.
