### ISSUE TITLE
FYI: qt5-5.9.2 coming

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#7991]
I'm working on `qt5-5.9.2` packaging.

There will be three new modules: `qt5-networkauth`, `qt5-purchasing` and `qt5-remoteobjects`.
This is probably relevant for the `python{,3}-PytQt5-*` packages.

The patchset required for musl changed a lot and I'm fighting with `ninja` and `gn`. This `gn` is now used instead of `gyp`, and its builtin allocator shim for intercepting glibc malloc/free of course won't work with musl libc. I need to somehow disable that in the `*-musl` builds.

x86_64 just finished building. i686 is next and x86_64-musl needs more fixes. Then cross building needs to be tested... a long way to go.

I wonder, if we need to revbump (all? many?) packages using `qt5-*-devel` packages after an update. How were the experiences with the previous qt5 minor revision change?

**Comment by pullmoll** [comment]
I came up with a somewhat _creative_ workaround for `allocator_shim_default_dispatch_to_glibc.cc` when building for musl libc. The musl libc does not export symbols like `__libc_malloc` etc. to call from the wrappers.

Instead of relying on these glibc symbol names, I use `void* libc = dlopen("libc.so", 0);` to get a handle to musl libc, then resolve its symbols using `funcptr = (t_funcptr) dlsym(libc, "malloc");` for the six memory functions. Finally the function pointers are called from the C++ wrappers and – funny enough – it seems as if this actually works; or perhaps it isn't used at all.

At least bootstrapping `gn` worked and now qtwebengine is built... oh, well, up to 8548 of 18333 files.
Next problem to fix: `about_credits.bro`

```
// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "base/allocator/allocator_shim.h"

#include <malloc.h>

#if defined(__GLIBC__)
// This translation unit defines a default dispatch for the allocator shim which
// routes allocations to libc functions.
// The code here is strongly inspired from tcmalloc's libc_override_glibc.h.

extern "C" {
void* __libc_malloc(size_t size);
void* __libc_calloc(size_t n, size_t size);
void* __libc_realloc(void* address, size_t size);
void* __libc_memalign(size_t alignment, size_t size);
void __libc_free(void* ptr);
}  // extern "C"

namespace {

using base::allocator::AllocatorDispatch;

void* GlibcMalloc(const AllocatorDispatch*, size_t size) {
  return __libc_malloc(size);
}

void* GlibcCalloc(const AllocatorDispatch*, size_t n, size_t size) {
  return __libc_calloc(n, size);
}

void* GlibcRealloc(const AllocatorDispatch*, void* address, size_t size) {
  return __libc_realloc(address, size);
}

void* GlibcMemalign(const AllocatorDispatch*, size_t alignment, size_t size) {
  return __libc_memalign(alignment, size);
}

void GlibcFree(const AllocatorDispatch*, void* address) {
  __libc_free(address);
}

size_t GlibcGetSizeEstimate(const AllocatorDispatch*, void* address) {
  // TODO(siggi, primiano): malloc_usable_size may need redirection in the
  //     presence of interposing shims that divert allocations.
  return malloc_usable_size(address);
}

}  // namespace

const AllocatorDispatch AllocatorDispatch::default_dispatch = {
    &GlibcMalloc,          /* alloc_function */
    &GlibcCalloc,          /* alloc_zero_initialized_function */
    &GlibcMemalign,        /* alloc_aligned_function */
    &GlibcRealloc,         /* realloc_function */
    &GlibcFree,            /* free_function */
    &GlibcGetSizeEstimate, /* get_size_estimate_function */
    nullptr,               /* next */
};

#else // defined(__GLIBC__)

#include <dlfcn.h>

extern "C" {
// Declare function pointers to the memory functions
typedef void* (*t_libc_malloc)(size_t size);
typedef void* (*t_libc_calloc)(size_t n, size_t size);
typedef void* (*t_libc_realloc)(void* address, size_t size);
typedef void* (*t_libc_memalign)(size_t alignment, size_t size);
typedef void (*t_libc_free)(void* ptr);
typedef size_t (*t_libc_malloc_usable_size)(void* ptr);

// Static instances of pointers to libc.so dl symbols
static t_libc_malloc libc_malloc = nullptr;
static t_libc_calloc libc_calloc = nullptr;
static t_libc_realloc libc_realloc = nullptr;
static t_libc_memalign libc_memalign = nullptr;
static t_libc_free libc_free = nullptr;
static t_libc_malloc_usable_size libc_malloc_usable_size = nullptr;
}  // extern "C"

namespace {

using base::allocator::AllocatorDispatch;

// resolve the symbols in libc.so
void musl_libc_memory_init()
{
  void* libc = dlopen("libc.so", 0);
  libc_malloc = (t_libc_malloc) dlsym(libc, "malloc");
  libc_calloc = (t_libc_calloc) dlsym(libc, "calloc");
  libc_realloc = (t_libc_realloc) dlsym(libc, "realloc");
  libc_memalign = (t_libc_memalign) dlsym(libc, "memalign");
  libc_free = (t_libc_free) dlsym(libc, "free");
  libc_malloc_usable_size = (t_libc_malloc_usable_size) dlsym(libc, "malloc_usable_size");
  dlclose(libc);
}

void* MuslMalloc(const AllocatorDispatch*, size_t size) {
  if (nullptr == libc_malloc)
    musl_libc_memory_init();
  return (*libc_malloc)(size);
}

void* MuslCalloc(const AllocatorDispatch*, size_t n, size_t size) {
  if (nullptr == libc_malloc)
    musl_libc_memory_init();
  return (*libc_calloc)(n, size);
}

void* MuslRealloc(const AllocatorDispatch*, void* address, size_t size) {
  if (nullptr == libc_malloc)
    musl_libc_memory_init();
  return (*libc_realloc)(address, size);
}

void* MuslMemalign(const AllocatorDispatch*, size_t alignment, size_t size) {
  if (nullptr == libc_malloc)
    musl_libc_memory_init();
  return (*libc_memalign)(alignment, size);
}

void MuslFree(const AllocatorDispatch*, void* address) {
  if (nullptr == libc_malloc)
    musl_libc_memory_init();
  (*libc_free)(address);
}

size_t MuslGetSizeEstimate(const AllocatorDispatch*, void* address) {
  // TODO(siggi, primiano): malloc_usable_size may need redirection in the
  //     presence of interposing shims that divert allocations.
  if (nullptr == libc_malloc)
    musl_libc_memory_init();
  return (*libc_malloc_usable_size)(address);
}

}  // namespace

const AllocatorDispatch AllocatorDispatch::default_dispatch = {
    &MuslMalloc,           /* alloc_function */
    &MuslCalloc,           /* alloc_zero_initialized_function */
    &MuslMemalign,         /* alloc_aligned_function */
    &MuslRealloc,          /* realloc_function */
    &MuslFree,             /* free_function */
    &MuslGetSizeEstimate,  /* get_size_estimate_function */
    nullptr,               /* next */
};

#endif

```

**Comment by ebfe** [comment]
This looks like the same problem as in the chromium builds. patches from there might help.

**Comment by ebfe** [comment]
about_credits.bro can be fixed by disabling gold.

**Comment by pullmoll** [comment]
Ah, `gold` was the problem. I was just trying to use the system /usr/bin/brotli instead...

**Comment by pullmoll** [comment]
Cross build for aarch64 fails with:
```
…
[330/330] LINK gn
Building gn manually in a temporary directory for bootstrapping...
Building gn using itself to out/Release...
Traceback (most recent call last):
  File "/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src/3rdparty/chromium/tools/gn/bootstrap/bootstrap.py", line 763, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src/3rdparty/chromium/tools/gn/bootstrap/bootstrap.py", line 126, in main
    return run_build(build_dir, options)
  File "/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src/3rdparty/chromium/tools/gn/bootstrap/bootstrap.py", line 87, in run_build
    build_gn_with_gn(temp_gn, build_root, options)
  File "/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src/3rdparty/chromium/tools/gn/bootstrap/bootstrap.py", line 748, in build_gn_with_gn
    check_call(cmd)
  File "/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src/3rdparty/chromium/tools/gn/bootstrap/bootstrap.py", line 44, in check_call
    subprocess.check_call(cmd, cwd=GN_ROOT, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
Project ERROR: GN build error!
make[3]: *** [Makefile:63: sub-gn-pro-make_first] Error 3
make[3]: Leaving directory '/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src/buildtools'
make[2]: *** [Makefile:53: sub-buildtools-make_first] Error 2
make[2]: Leaving directory '/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src'
make[1]: *** [Makefile:47: sub-src-make_first] Error 2
make[1]: Leaving directory '/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine'
make: *** [Makefile:974: module-qtwebengine-make_first] Error 2
=> ERROR: qt5-5.9.2_1: failed to run do_build() at line 13.
```

It seems as if we need a system `gn` built for the host to build `gn` for the target, or fix the bootstrap to build a host `gn` first, then use that to cross build the target `gn`.

**Comment by pullmoll** [comment]
Next error when trying to bootstrap gn:
```
[330/330] LINK gn
ERROR at //remoting/remoting_version.gni:48:11: Script returned non-zero exit code.
_result = exec_script(_version_py_abspath,
          ^----------
Current dir: /builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src/3rdparty/chromium/out/Release/
Command: /usr/bin/python2 -- /builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src/3rdparty/chromium/build/util/version.py -f ../../remoting/branding_Chromium -f ../../remoting/VERSION -t mac_host_bundle = "@MAC_HOST_BUNDLE_NAME@" mac_native_messaging_bundle = "@MAC_NATIVE_MESSAGING_HOST_BUNDLE_NAME@" mac_remote_assistance_bundle = "@MAC_REMOTE_ASSISTANCE_HOST_BUNDLE_NAME@" prefpane_bundle_name = "@MAC_PREFPANE_BUNDLE_NAME@" host_bundle_name = "@MAC_HOST_BUNDLE_NAME@" host_name= "@MAC_HOST_PACKAGE_NAME@" host_service_name = "@DAEMON_FILE_NAME@" bundle_prefix = "@MAC_UNINSTALLER_BUNDLE_PREFIX@" host_uninstaller_name = "@MAC_UNINSTALLER_NAME@" version_patch = "@REMOTING_PATCH@" 
Returned 1.
stderr:

Traceback (most recent call last):
  File "/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src/3rdparty/chromium/build/util/version.py", line 170, in <module>
    sys.exit(main())
  File "/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src/3rdparty/chromium/build/util/version.py", line 143, in main
    values = fetch_values(options.file, options.official)
  File "/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src/3rdparty/chromium/build/util/version.py", line 50, in fetch_values
    fetch_values_from_file(values, file_name)
  File "/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src/3rdparty/chromium/build/util/version.py", line 25, in fetch_values_from_file
    for line in open(file_name, 'r').readlines():
IOError: [Errno 2] No such file or directory: '../../remoting/branding_Chromium'

See //remoting/build/config/remoting_build.gni:11:1: whence it was imported.
import("//remoting/remoting_version.gni")
^---------------------------------------
See //remoting/BUILD.gn:5:1: whence it was imported.
import("//remoting/build/config/remoting_build.gni")
^--------------------------------------------------
See //BUILD.gn:355:15: which caused the file to be included.
    deps += [ "//remoting:remoting_all" ]
              ^------------------------
Command '['/tmp/tmpL593An/gn', 'gen', '/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src/3rdparty/chromium/out/Release', '--args=\n   is_clang=false\n   treat_warnings_as_errors=false\n   binutils_path="/usr/bin"\n   use_gold=false\n   use_sysroot=false\n   use_allocator="none"\n   use_allocator_shim=false is_debug=false', '--script-executable=/usr/bin/python2']' returned non-zero exit status 1
Building gn using itself to out/Release...
=> ERROR: qt5-5.9.2_1: failed to run pre_configure() at line 201.
```

At this early stage in `pre_configure()` perhaps files are missing which qt5 would create on the fly.
This is becoming a nightmare :cry:

**Comment by pullmoll** [comment]
One of the probably last problems to solve is that when re-building tools for the target arch (qmlmin, qmllint, qmlimportscanner) the linker does not find certain symbols:
```
aarch64-linux-musl-c++ -specs=/void-packages/common/environment/configure/gccspecs/hardened-ld -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pthread -ldl -fPIE -L/usr/aarch64-linux-musl/usr/lib -Wl,--no-keep-memory --sysroot=/usr/aarch64-linux-musl -Wl,--gc-sections -Wl,-O1 -Wl,--enable-new-dtags -Wl,-z,origin -Wl,-rpath,\$ORIGIN/../../ -specs=/void-packages/common/environment/configure/gccspecs/hardened-ld -Wl,-z,relro -Wl,-z,now -Wl,--as-needed    -pthread -ldl -fPIE -L/usr/aarch64-linux-musl/usr/lib -o /builddir/qt-everywhere-opensource-src-5.9.2/target/bin/qmlmin .obj/main.o   -L/builddir/qt-everywhere-opensource-src-5.9.2/qtdeclarative/lib -lQt5QmlDevTools -L/builddir/qt-everywhere-opensource-src-5.9.2/qtbase/lib -lQt5Core -lpthread
.obj/main.o: In function `QQmlJS::Minify::Minify(int)':
main.cpp:(.text+0x75c): undefined reference to `QQmlJS::Lexer::Lexer(QQmlJS::Engine*)'
main.cpp:(.text+0x778): undefined reference to `QQmlJS::Engine::Engine()'
.obj/main.o: In function `QQmlJS::Tokenize::Tokenize()':
main.cpp:(.text+0x7e4): undefined reference to `QQmlJS::Lexer::Lexer(QQmlJS::Engine*)'
main.cpp:(.text+0x7fc): undefined reference to `QQmlJS::Engine::Engine()'
.obj/main.o: In function `QQmlJS::Minify::parse(int)':
main.cpp:(.text+0x93c): undefined reference to `QQmlJSGrammar::action_default'
main.cpp:(.text+0x950): undefined reference to `QQmlJSGrammar::action_default'
main.cpp:(.text+0x954): undefined reference to `QQmlJSGrammar::action_index'
main.cpp:(.text+0x9c4): undefined reference to `QQmlJSGrammar::action_index'
main.cpp:(.text+0x9d0): undefined reference to `QQmlJSGrammar::action_check'
main.cpp:(.text+0x9d4): undefined reference to `QQmlJSGrammar::action_check'
```

The symbols are defined in libQt5Qml.so.5.9.2 and I don't know why they are not found. Probably something wrong with the `do_install()` cross build stage handling of project or Makefiles.

**Comment by ebfe** [comment]
> The symbols are defined in libQt5Qml.so.5.9.2 and I don't know why they are not found. 

`-Wl,--as-needed` and object order?

**Comment by pullmoll** [comment]
I could try to remove that. I'm currently trying to modify the Makefile to explicitly `-lQt5Qml` after the `-lQt5QmlDevTools`. If that fails, I'll try with modifying the linker flags.

**Comment by pullmoll** [comment]
Ok, with a specific `qmlmin.pro` file which lists `qml` and `network` as QT modules, I get as far as the only missing symbols are the ones defined in `qtdeclarative/src/qml/parser/qqmljsgrammar.cpp`.

They don't seem to be exported, probably because the `QT += qmldevtools-private` does not work in this stage, and I think the easiest way to solve this is to include this source file, which is a generated file, into the build of `qmlmin`, `qmllint` and `qmlimportscanner`.

Here's the `qmlmin.pro` file I used now, i.e. which I put in `srcpkgs/qt5/files/qmlmin.pro`:
```
QT       = core qml network qmldevtools-private
SOURCES += main.cpp

QMAKE_TARGET_PRODUCT = qmlmin
QMAKE_TARGET_DESCRIPTION = QML/JS minifier

win32 {
   VERSION = $${QT_VERSION}.0
} else {
   VERSION = $${QT_VERSION}
}

load(qt_tool)
```
Adding the source `qmljsgrammar.cpp` here is easy enough.
Now trying to see if that solves all issues.

**Comment by pullmoll** [comment]
Ok, the three candidates `qmlmin`, `qmllint` and `qmlimportscanner` now link, but a similar problem exists with lupdate ... and I'm willing to bet it will appear for lrelease and lconvert as well ;-P

**Comment by pullmoll** [comment]
Ok, I got it working.
Now we can go on with #8002

**Comment by pullmoll** [comment]
I need to reopen this one. When cross building for armv7hf I get:

```
ERROR at //build/config/android/internal_rules.gni:11:1: Assertion failed.
assert(is_android)
^-----
See //build/config/android/rules.gni:8:1: whence it was imported.
import("//build/config/android/internal_rules.gni")
^-------------------------------------------------
See //third_party/android_tools/BUILD.gn:5:1: whence it was imported.
import("//build/config/android/rules.gni")
^----------------------------------------
See //third_party/openmax_dl/dl/BUILD.gn:199:16: which caused the file to be included.
      deps = [ "//third_party/android_tools:cpu_features" ]
               ^-----------------------------------------
Project ERROR: GN run error!
make[3]: *** [Makefile:80: sub-gn_run-pro-make_first] Error 3
make[3]: Leaving directory '/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src/core'
make[2]: *** [Makefile:78: sub-core-make_first] Error 2
make[2]: Leaving directory '/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine/src'
make[1]: *** [Makefile:47: sub-src-make_first] Error 2
make[1]: Leaving directory '/builddir/qt-everywhere-opensource-src-5.9.2/qtwebengine'
make: *** [Makefile:974: module-qtwebengine-make_first] Error 2
=> ERROR: qt5-5.9.2_1: failed to run do_build() at line 13.
```

**Comment by pullmoll** [comment]
Funny fact: The detection of ARMv7 Neon requires Android tools for a log_printf! This is by all means a really, really stupid idea, if you ask me.
I'll patch it away so we can have Neon detection without becoming Android :)

**Comment by pullmoll** [comment]
Argh... I'm sick of this ;)
I think I'll disable opus for Webengine, as qt5 configure now has an option to do this.
Reading chromium's template it seems the system opus is not usable.

**Comment by pullmoll** [comment]
Next one: webengine compiler selection in `qtwebengine/src/3rdparty/chromium/build/config/compiler/BUILD.gn` is broken. It tries to cross compile (some) files using the host compiler and x86 flags when the target is really armv7hf.

```
[6337/15721] CXX v8_snapshot/obj/v8/mkpeephole/bytecode-operands.o
FAILED: v8_snapshot/obj/v8/mkpeephole/bytecode-operands.o 
/usr/lib/ccache/bin/g++ -MMD -MF v8_snapshot/obj/v8/mkpeephole/bytecode-operands.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DNO_TCMALLOC -DDISABLE_NACL -DENABLE_TASK_MANAGER=1 -DENABLE_THEMES=1 -DUSE_PROPRIETARY_CODECS -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DTOOLKIT_QT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DV8_I18N_SUPPORT -DV8_TARGET_ARCH_ARM -DCAN_USE_ARMV7_INSTRUCTIONS -DCAN_USE_VFP3_INSTRUCTIONS -DUSE_EABI_HARDFLOAT=1 -Iv8_snapshot/gen -I../../3rdparty/chromium -I../../3rdparty/chromium/v8/include -Iv8_snapshot/gen/v8/include -I../../3rdparty/chromium/v8 -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m32 -msse2 -mfpmath=sse -mmmx -g0 -fvisibility=hidden -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-unused-parameter -O3 -fno-ident -fdata-sections -ffunction-sections -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -fno-delete-null-pointer-checks -fno-rtti -fno-exceptions -Wno-deprecated -Wno-narrowing -c ../../3rdparty/chromium/v8/src/interpreter/bytecode-operands.cc -o v8_snapshot/obj/v8/mkpeephole/bytecode-operands.o
In file included from /usr/include/features.h:447:0,
                 from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdint.h:26,
                 from /usr/lib/gcc/x86_64-unknown-linux-gnu/6.3/include/stdint.h:9,
                 from ../../3rdparty/chromium/v8/src/globals.h:9,
                 from ../../3rdparty/chromium/v8/src/interpreter/bytecode-operands.h:8,
                 from ../../3rdparty/chromium/v8/src/interpreter/bytecode-operands.cc:5:
/usr/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
 # include <gnu/stubs-32.h>
                           ^
compilation terminated.
```

**Comment by pullmoll** [comment]
I'm stuck with that issue. I can't find a way to convince qtwebengine v8 build to use sane values for the target. It tries to build parts (bytecode) using i686 as the target (i.e. native g++ with -m32).

It seems that somehow our e.g. armv7hf target cpu name is not well perceived by the scripts which make a target architecture from a cross-compiler name. It obviously works ok for aarch64, but not for armv{6,7}hf. I'd be happy if someone with new ideas could take a look at PR #8002.

**Comment by pullmoll** [comment]
Is there some way to *downgrade* an x86_64 environment to i686?
I ask because the cross build of qt5 for armv6hf and armv7hf is ok when run in a i686 build environment.
It seems that the difference in the size of pointers makes the difference here: i686 and armv6hf both have 32 bit pointers, while x86_64 has 64 bit.

**Comment by pullmoll** [comment]
Waiting for #8002 to be addressed.
