### ISSUE TITLE
python-M2Crypto-0.27.0_1: _m2crypto.so: undefined symbol: BIO_meth_set_gets

### ISSUE THREAD

**Issue by paoloschi** [voidlinux/void-packages#8168]
Void Linux x86_64 full up-to-date
python-2.7.14_1

for a long time now I've run from Void the [acestream](http://dl.acestream.org/linux/acestream_3.1.16_debian_8.7_x86_64.tar.gz) engine (a python2 application) that worked well for me until the __python-M2Crypto__ package was updated to __v0.27.0_1__ a few days ago..

```
$ /opt/acestream/acestreamengine --lib-path /opt/acestream --client-console
2017-10-14 21:53:30,546|MainThread|acestream|error during startup
Traceback (most recent call last):
  File "core.c", line 1590, in 
  File "core.c", line 144, in 
  File "core.c", line 86, in 
  File "/usr/lib/python2.7/site-packages/M2Crypto/__init__.py", line 26, in <module>
    from M2Crypto import (ASN1, AuthCookie, BIO, BN, DH, DSA, EVP, Engine, Err,
  File "/usr/lib/python2.7/site-packages/M2Crypto/ASN1.py", line 15, in <module>
    from M2Crypto import BIO, m2, util
  File "/usr/lib/python2.7/site-packages/M2Crypto/BIO.py", line 10, in <module>
    from M2Crypto import m2, six, util
  File "/usr/lib/python2.7/site-packages/M2Crypto/m2.py", line 30, in <module>
    from M2Crypto.m2crypto import *
  File "/usr/lib/python2.7/site-packages/M2Crypto/m2crypto.py", line 17, in <module>
    _m2crypto = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/M2Crypto/m2crypto.py", line 16, in swig_import_helper
    return importlib.import_module('_m2crypto')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _m2crypto
```

and in fact a `_m2crypto.py` file does not exist in `/usr/lib/python2.7/site-packages/M2Crypto`.
I had a similar error several versions ago, that I had solved it by adding a link (I'm not a developer so I hope what I'm going to write here can make sense...)

so, I've tried with the symbolic link `/usr/lib/python2.7/site-packages/M2Crypto/_m2crypto.py` --> `/usr/lib/python2.7/site-packages/M2Crypto/m2crypto.py` without success.
But when I thought about moving my newly created link from `/usr/lib/python2.7/site-packages/M2Crypto` up in `/usr/lib/python2.7/site-packages` the situation changed as you can see in this second error log...

```
$ /opt/acestream/acestreamengine --lib-path /opt/acestream --client-console
2017-10-14 21:58:02,994|MainThread|acestream|error during startup
Traceback (most recent call last):
  File "core.c", line 1590, in 
  File "core.c", line 144, in 
  File "core.c", line 86, in 
  File "/usr/lib/python2.7/site-packages/M2Crypto/__init__.py", line 26, in <module>
    from M2Crypto import (ASN1, AuthCookie, BIO, BN, DH, DSA, EVP, Engine, Err,
  File "/usr/lib/python2.7/site-packages/M2Crypto/ASN1.py", line 15, in <module>
    from M2Crypto import BIO, m2, util
  File "/usr/lib/python2.7/site-packages/M2Crypto/BIO.py", line 10, in <module>
    from M2Crypto import m2, six, util
  File "/usr/lib/python2.7/site-packages/M2Crypto/m2.py", line 30, in <module>
    from M2Crypto.m2crypto import *
  File "/usr/lib/python2.7/site-packages/M2Crypto/m2crypto.py", line 45, in <module>
    from _m2crypto import *
ImportError: /usr/lib/python2.7/site-packages/M2Crypto/_m2crypto.so: undefined symbol: BIO_meth_set_gets
```
here the problem seems to have to do with the package compilation and then I decided to ask for help, provided the problem resides in python-M2Crypto package but, as I wrote, everything had always worked well __up to Void python-M2Crypto v0.26.4__ when executing the exactly same command..

**Comment by ebfe** [comment]
Seems it's missing the _m2crypto.so older packages shipped.

**Comment by ebfe** [comment]
Hmm, no _m2crypto.so is there, but somehow isn't picked up anymore
```
>>> import M2Crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/M2Crypto/__init__.py", line 26, in <module>
    from M2Crypto import (ASN1, AuthCookie, BIO, BN, DH, DSA, EVP, Engine, Err,
  File "/usr/lib/python2.7/site-packages/M2Crypto/ASN1.py", line 15, in <module>
    from M2Crypto import BIO, m2, util
  File "/usr/lib/python2.7/site-packages/M2Crypto/BIO.py", line 10, in <module>
    from M2Crypto import m2, six, util
  File "/usr/lib/python2.7/site-packages/M2Crypto/m2.py", line 30, in <module>
    from M2Crypto.m2crypto import *
  File "/usr/lib/python2.7/site-packages/M2Crypto/m2crypto.py", line 17, in <module>
    _m2crypto = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/M2Crypto/m2crypto.py", line 16, in swig_import_helper
    return importlib.import_module('_m2crypto')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _m2crypto

```

**Comment by asergi** [comment]
```
0.26.2 - 2017-09-20
-------------------
- port to support OpenSSL 1.1.0 API
```
