### ISSUE TITLE
segfault in ARM js24 since commit 822a60742a8cc324ad54d3a60fd9cb8026763c57

### ISSUE THREAD

**Issue by moinejf** [voidlinux/void-packages#9303]
### System

* xuname:
  Void 4.9.0-rc1-dirty armv7l  uptodate rrF
* package:
  mozjs24-24.2.0_7

### Expected behavior
js24 was runing fine before the commit.

### Actual behavior

When running some complex script, js24 receives SIGSEGV:

```
$ gdb --args js24 abcjs24 /home/jef/abcm2ps/voices.abc                         
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "armv7l-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from js24...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/js24 abcjs24 /home/jef/abcm2ps/voices.abc
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0xb69ac450 (LWP 1304)]
[New Thread 0xb618b450 (LWP 1305)]

Thread 1 "js24" received signal SIGSEGV, Segmentation fault.
0x7f8a2dbc in ?? ()
(gdb) where
#0  0x7f8a2dbc in ?? ()
#1  0x7f7ee894 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

The same script run by jsc-1 (package webkitgtk2-2.4.11_5) or d8 (package v8-3.24.35.33_3) works correctly.

### Steps to reproduce the behavior

The script is available getting the package 'abc2svg' by npm.
The crash occurs when the ABC file contains more than 2 tunes.

**Comment by pullmoll** [comment]
Can you give mozjs24-24.2.0_8 a try? If it still crashed, it would be good to have the detailed debug information, which you can get by first installing void-repo-debug and then mozjs24-dbg packages.

**Comment by moinejf** [comment]
Fine! No problem anymore.
Many thanks.
